<?php
session_start();
$_SESSION['loadmore']=null;
?>
<!doctype html>
<html lang="en-us" dir="ltr">
<head>
<meta charset='utf-8'>
<title>Leonard Shawls and Scarves</title>
<link rel='icon' type='image/x-icon' href='https://www.leonardscarf.com/favicon.ico'>
<link rel="canonical" href="https://www.leonardscarf.com/en/index.php" />
<link rel="alternate" href="https://www.leonardscarf.com/index.php" hreflang="fa-ir" />
<link rel="alternate" href="https://www.leonardscarf.com/en/index.php" hreflang="en-us" />
<meta name='description' content="Leonard scarf is an iranian fashion brand of womens scarves and shawls, there are lots of variety of design and colors
that making excellent looks for everyone">
<meta content='width=device-width, initial-scale=1.0' name='viewport'>
<meta name='keywords' content='shawl and scarf,shawl,scarf,shop,buy,new'>
<meta name='author' content='mohsen bashirzadeh'>
<meta name="wot-verification" content="e07ff571dc2b59f09b95">
<meta property="fb:app_id" content="1066691580080256" />
<meta property="fb:admins" content="leonardscarf,leonardazin"/>
<meta property="og:image" content="https://www.leonardscarf.com/images/new/scarf-8.jpg" />
<meta property="og:title" content="Leonard Shawls and Scarves" />
<meta property="og:url" content="https://www.leonardscarf.com" />
<meta property="og:description" content='Leonard scarf is an iranian fashion brand of womens scarves and shawls, there are lots of variety of design and colors
that making excellent looks for everyone' />
<meta property="og:type" content="website" />
<!-- for leonard -->
<link rel="stylesheet" type="text/css" href="../css/leonard-en.css" />
<link rel="stylesheet" type="text/css" href="../slide/engine1/style.css" />
<script type="text/javascript" src="../slide/engine1/jquery.js"></script>
<script type="text/javascript" src="../js/leonard.js"></script>
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type='application/ld+json'>
{
"@context": "https://www.schema.org",
"@type": "ClothingStore",
"name": "Leonard Shawls and Scarves",
"url": "https://www.leonardscarf.com",
"logo": "https://www.leonardscarf.com/favicon.ico",
"image": "https://www.leonardscarf.com/images/new/scarf-8.jpg",
"description": "Leonard scarf is an iranian fashion brand of womens scarves and shawls, there are lots of variety of design and colors that making excellent looks for everyone",
"address": {
"@type": "PostalAddress",
"streetAddress": "No.24 Main row jafari bazar St. 15 khordad",
"addressLocality": "Tehran",
"addressRegion": "Tehran",
"postalCode": "13567",
"addressCountry": "Iran"
},
"geo": {
"@type": "GeoCoordinates",
"latitude": "35.675612",
"longitude": "51.423744"
},
"openingHours": "Mo 07:00-08:00 Tu, We, Sa, Su 07:00-20:00 Th 07:00-13:00",
"contactPoint": {
"@type": "ContactPoint",
"telephone": "+982155555555",
"contactType": "customer support"
}
}
{
"@context": "https://www.schema.org",
"@type": "WebSite",
"name": "Leonard Shawls and Scarves",
"alternateName": "Shawls and Scarves",
"url": "https://www.leonardscarf.com"
}
</script>
</head>
<body>
<?php include_once("../analyticstracking.php") ?>
<header class="header-distributed">
<div class="header-center">
<h1>Leonard<strong> Shawls and Scarves</strong></h1>
</div>
<div class="langdiv">
<h2>Change Language</h2><hr /><h2><span><a href="https://www.leonardscarf.com/en/" hreflang="en" title="English">English </a>|<a href="https://www.leonardscarf.com" hreflang="ir-fa" title="Persian"> Persian</a></span></h2>
</div>
<hr class="style-two">
</header>
<div id="wowslider-container1">
<div class="ws_images"><ul>
<li><img src="../slide/data1/images/s2.jpg" alt="winter Shawl" title="winter Shawl" id="wows1_0"/></li>
<li><img src="../slide/data1/images/s3.jpg" alt="winter Scarf" title="winter Scarf" id="wows1_1"/></li>
<li><img src="../slide/data1/images/s4.jpg" alt="winter Shawl and Scarf" title="winter Shawl and Scarf" id="wows1_2"/></li>
</ul></div></div>
<script type="text/javascript" src="../slide/engine1/wowslider.js"></script>
<script type="text/javascript" src="../slide/engine1/script.js"></script>
<nav>
<ul itemscope itemtype="http://www.schema.org/SiteNavigationElement">
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com" title="Go to Home">Main Page<br /> <small>Shawl and Scarves</small></a></li>
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com/search/" title="Search in shawls and scarves">Search<br /> <small>All Archive</small></a></li>
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com/scarf/" title="Search in Scarves">Scarves<br /> <small>Scarves Search</small></a></li>
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com/shawl/" title="Search in Shawls">Shawls<br /> <small>Shawls Search</small></a></li>
<?php if (!isset($_SESSION['usernamelogin'])) { ?>
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com/register/register" title="you can Register Here">Register<br /> <small>Membership</small></a></li>
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com/register/loginuser" title="User can Login Here">Login<br /> <small>User</small></a></li>
<?php } else { 	?>
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com/register/logout" title="for Logout Click here"><?php echo $_SESSION['usernamelogin']; ?><br /> <small>Logout</small></a></li>
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com/pricelist" title="to View Price List">Price List<br /> <small>Shawl and Scarves</small></a></li>
<?php } ?>
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com/contactus"title="for Contact Us click here">Contact us<br /> <small>Call us</small></a></li>
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com/about" title="to know more about us">About Us<br /> <small>Description</small></a></li>
</ul>
</nav>
<!--page_container-->
<h2 class="rules">Short Description about Leonard
<strong>Shawls and Scarves</strong></h2>
<h3 class="content">It's an honor that we have leading component
the best manufactures  in the last 3 years…
Now Leonard Azin company
relying on long history of clothing and
fashion industry , distribute their products Across country  and
also have been covered many the best shops…
</h3>
<h4 class="one"><span>Latest<strong> Shawls and Scarves</strong></span></h4>
<div class="container">
<div class="main">
<div id="most-view" class="mi-slider">
<ul>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-20"><img src="https://www.leonardscarf.com/images/scarf/cotton/20/scarf-cotton-20-jade-200.jpg" alt="Leonard Shawls and Scarves" title="Leonard Shawls and Scarves"><h4>two Rug edge Cotton Scarf</h4></a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-19"><img src="https://www.leonardscarf.com/images/scarf/cotton/19/scarf-cotton-19-gray-200.jpg" alt="Gucci Pattern Cotton Scarf" title="Gucci Pattern Cotton Scarf"><h4>Gucci Pattern Cotton Scarf</h4></a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-18"><img src="https://www.leonardscarf.com/images/scarf/cotton/18/scarf-cotton-18-pink-200.jpg" alt="Rug edge Pattern Cotton Scarf" title="Rug edge Pattern Cotton Scarf"><h4>Rug edge Pattern Cotton Scarf</h4></a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-17"><img src="https://www.leonardscarf.com/images/scarf/cotton/17/scarf-cotton-17-red-200.jpg" alt="Owl Pattern Cotton Scarf" title="Owl Pattern Cotton Scarf"><h4>Owl Pattern Cotton Scarf</h4></a></li>
</ul>
<ul>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-19"><img src="https://www.leonardscarf.com/images/shawl/cotton/19/shawl-cotton-19-org-200.jpg" alt="Simple Long Cotton Shawl" title="Simple Long Cotton Shawl"><h4>Simple Long Cotton Shawl</h4></a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-21"><img src="https://www.leonardscarf.com/images/shawl/cotton/21/shawl-cotton-21-silver-200.jpg" alt="Pleated Cotton Shawl" title="Pleated Cotton Shawl"><h4>Pleated Cotton Shawl</h4></a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-20"><img src="https://www.leonardscarf.com/images/shawl/cotton/20/shawl-cotton-20-red-200.jpg" alt="Watercolor edge Shawl" title="Watercolor edge Shawl"><h4>Watercolor edge Shawl</h4></a></li>
</ul>
<nav>
<a href="">Scarves</a>
<a href="">Shawls</a>
</nav>
</div>
</div>
</div><!-- /container -->
<h2 class="rules"><strong>Scarf </strong>describes :</h2>
<h3 class="content">Scarves come in many shapes, sizes and, importantly, fabrics. A scarf’s fabrication determines its texture, appearance, and weather-appropriateness, so you should always pay attention to fabric when you’re shopping for scarves.</h3>
<script src="../js/slider/jquery.catslider.js"></script>
<script>
$(function() {$( '#most-view' ).catslider();});
</script>
<footer class="footer-distributed" dir="ltr">
<hr class="style-one">
<div class="footer-left">
<h3>Leonard<span>Scarf</span></h3>
<p class="footer-links">
<a href="https://www.leonardscarf.com/index">Main Page</a>&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/register/register">Register</a>&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/register/loginuser">Login</a>&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/contactus">Contact us</a>&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/about">About us</a>&nbsp;&nbsp;
</p>
<p class="footer-company-name">»Leonard Scarf &copy; 2015</p>
</div>
<div class="footer-center">
<div>
<i class="fa fa-map-marker"></i>
<p>Iran Tehran<span>No.3 alley tekie beinol haramein St. 15 khordad</span></p>
</div>
<div>
<i class="fa fa-phone"></i>
<p dir="ltr">+982155555555</p>
</div>
<div>
<i class="fa fa-envelope"></i>
<p><a href="mailto:admin@leonardscarf.com.com">admin@leonardscarf.com</a></p>
</div>
</div>
<div class="footer-right">
<p class="footer-company-about">
<span><a href="https://www.leonardscarf.com/about">About Leonard Copany</a></span>
Leonard is Best Brand of Shawl and Scarf
</p>
<div class="footer-icons">
<a href="https://www.facebook.com/leonardazin"><i class="fa fa-facebook"></i></a>
<a href="https://telegram.me/joinchat/CEmNSjvmKuhulUtqyqAMNA"><i class="fa fa-paper-plane"></i></a>
<a href="https://www.instagram.com/leonardscarf/?ref=badge"><i class="fa fa-instagram"></i></a>
<a href="https://plus.google.com/118304422008766935997"><i class="fa fa-google"></i></a>
</div>
</div>
</footer>
<div class="footer-up">
<hr class="style-two">
<div class="footer-center" dir="rtl">
<p class="footer-links">
<a href="https://www.leonardscarf.com/honours">Honours</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/rules">Rules and Regulations</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/complaints">Complaints</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/sitemap.php">Site Map</a>&nbsp;&nbsp;&nbsp;&nbsp;
</p>
</div>
</div>
</body>
</html>