<?php
session_start();
$_SESSION['loadmore']=null;
if (substr_count($_SERVER['HTTP_ACCEPT_ENCODING'], 'gzip')) ob_start("ob_gzhandler"); else ob_start(); ?>
<!doctype html>
<html lang="fa-ir">
<head>
<meta charset='utf-8'>
<title>شال - روسری | شال و روسری لئونارد</title>
<link rel='icon' type='image/x-icon' href='https://www.leonardscarf.com/favicon.ico'>
<link rel="canonical" href="https://www.leonardscarf.com"/>
<link rel="alternate" href="https://www.leonardscarf.com/index.php" hreflang="fa-ir" />
<link rel="alternate" href="https://www.leonardscarf.com/en/index.php" hreflang="en-us" />
<link rel="amphtml" href="https://www.leonardscarf.com/index-amp.php" />
<meta name='description' content='لئونارد برترین برند انواع شال و روسری با ارائه بهترین کیفیت و طراحی و رنگ بندی فوق العاده همتراز با برندهای بزرگ جهان دارای نمایندگی رسمی توزیع شال و پخش روسری.'>
<meta content='width=device-width, initial-scale=1.0' name='viewport'>
<meta name='keywords' content='شال و روسری , شال , روسری , لئونارد'>
<meta name='author' content='mohsen bashirzadeh'>
<meta name="wot-verification" content="e07ff571dc2b59f09b95">
<meta property="fb:app_id" content="1066691580080256" />
<meta property="fb:admins" content="leonardscarf,leonardazin"/>
<meta property="og:image" content="https://www.leonardscarf.com/images/scarf/cotton/20/scarf-cotton-20-jade-200.jpg" />
<meta property="og:title" content="شال و روسری لئونارد" />
<meta property="og:url" content="https://www.leonardscarf.com" />
<meta property="og:description" content='لئونارد برترین برند انواع شال و روسری با ارائه بهترین کیفیت و طراحی و رنگ بندی فوق العاده همتراز با برندهای بزرگ جهان دارای نمایندگی رسمی توزیع شال و پخش روسری.' />
<meta property="og:type" content="website" />
<!-- for leonard -->
<link rel="stylesheet" type="text/css" href="css/leonard.css" />
<link rel="stylesheet" type="text/css" href="slide/engine1/style.css" />
<script type="text/javascript" src="slide/engine1/jquery.js"></script>
<script type="text/javascript" src="js/leonard.js"></script>
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type='application/ld+json'>
{
"@context": "https://www.schema.org",
"@type": "ClothingStore",
"name": "شال و روسری لئونارد",
"url": "https://www.leonardscarf.com",
"logo": "https://www.leonardscarf.com/favicon.ico",
"image": "https://www.leonardscarf.com/images/new/scarf-8.jpg",
"description": "لئونارد برترین برند انواع شال و روسری با ارائه بهترین کیفیت و طراحی و رنگ بندی فوق العاده همتراز با برندهای بزرگ جهان دارای نمایندگی رسمی در سراسر کشور",
"address": {
"@type": "PostalAddress",
"streetAddress": "خیابان 15 خرداد ,بازار جعفری , راسته اصلی , پلاک 24",
"addressLocality": "تهران",
"addressRegion": "تهران",
"postalCode": "13567",
"addressCountry": "ایران"
},
"geo": {
"@type": "GeoCoordinates",
"latitude": "35.675612",
"longitude": "51.423744"
},
"openingHours": "Mo 07:00-08:00 Tu, We, Sa, Su 07:00-20:00 Th 07:00-13:00",
"contactPoint": {
"@type": "ContactPoint",
"telephone": "+982155555555",
"contactType": "customer support"
}
}
</script>
<script type='application/ld+json'>
{
"@context": "https://www.schema.org",
"@type": "WebSite",
"name": "شال و روسری لئونارد",
"alternateName": "شال و روسری",
"url": "https://www.leonardscarf.com"
}
</script>
<script type='application/ld+json'>
[ {
"@context" : "https://schema.org",
"@type" : "Product",
"name" : "[شال و روسری لئونارد] روسری طرح گل درشت",
"description" : "لئونارد ارائه کننده برترین مدلهای شال و روسری",
"brand" : {
"@type" : "Brand",
"name" : "شال و روسری لئونارد",
"logo" : "https://www.leonardscarf.com/favicon.ico"
},
"offers" : {
"@type" : "Offer",
"price" : "45000"
}
}, {
"@context" : "https://schema.org",
"@type" : "Product",
"name" : "[شال و روسری لئونارد] روسری چهارخانه",
"description" : "لئونارد ارائه کننده برترین مدلهای شال و روسری",
"brand" : {
"@type" : "Brand",
"name" : "شال و روسری لئونارد",
"logo" : "https://www.leonardscarf.com/favicon.ico"
},
"offers" : {
"@type" : "Offer",
"price" : "45000"
}
}, {
"@context" : "https://schema.org",
"@type" : "Product",
"name" : "[شال و روسری لئونارد] روسری لنین ساده",
"description" : "لئونارد ارائه کننده برترین مدلهای شال و روسری",
"brand" : {
"@type" : "Brand",
"name" : "شال و روسری لئونارد",
"logo" : "https://www.leonardscarf.com/favicon.ico"
},
"offers" : {
"@type" : "Offer",
"price" : "45000"
}
}, {
"@context" : "https://schema.org",
"@type" : "Product",
"name" : "[شال و روسری لئونارد] روسری طرح لوئیز ویتون",
"description" : "لئونارد ارائه کننده برترین مدلهای شال و روسری",
"brand" : {
"@type" : "Brand",
"name" : "شال و روسری لئونارد",
"logo" : "https://www.leonardscarf.com/favicon.ico"
},
"offers" : {
"@type" : "Offer",
"price" : "45000"
}
}, {
"@context" : "https://schema.org",
"@type" : "Product",
"name" : "[شال و روسری لئونارد] روسری 4 طرح گوشه",
"description" : "لئونارد ارائه کننده برترین مدلهای شال و روسری",
"brand" : {
"@type" : "Brand",
"name" : "شال و روسری لئونارد",
"logo" : "https://www.leonardscarf.com/favicon.ico"
},
"offers" : {
"@type" : "Offer",
"price" : "45000"
}
}, {
"@context" : "https://schema.org",
"@type" : "Product",
"name" : "[شال و روسری لئونارد] روسری طرح سنتی",
"description" : "لئونارد ارائه کننده برترین مدلهای شال و روسری",
"brand" : {
"@type" : "Brand",
"name" : "شال و روسری لئونارد",
"logo" : "https://www.leonardscarf.com/favicon.ico"
},
"offers" : {
"@type" : "Offer",
"price" : "45000"
}
}, {
"@context" : "https://schema.org",
"@type" : "Product",
"name" : "[شال و روسری لئونارد] روسری خط و خال",
"description" : "لئونارد ارائه کننده برترین مدلهای شال و روسری",
"brand" : {
"@type" : "Brand",
"name" : "شال و روسری لئونارد",
"logo" : "https://www.leonardscarf.com/favicon.ico"
},
"offers" : {
"@type" : "Offer",
"price" : "45000"
}
}, {
"@context" : "https://schema.org",
"@type" : "Product",
"name" : "[شال و روسری لئونارد] روسری طرح سنتی",
"description" : "لئونارد ارائه کننده برترین مدلهای شال و روسری",
"brand" : {
"@type" : "Brand",
"name" : "شال و روسری لئونارد",
"logo" : "https://www.leonardscarf.com/favicon.ico"
},
"offers" : {
"@type" : "Offer",
"price" : "45000"
}
} ]
</script>
</head>
<body>
<header class="header-distributed">
<div class="header-center">
<h1><strong>شال و روسری</strong> لئونارد </h1>
</div>
<div class="header-left">
<h2>Leonard<span>Scarf</span></h2>
</div>
<div class="langdiv">
<h2>تغییر زبان</h2><hr /><h2><span><a href="https://www.leonardscarf.com/en/" hreflang="en-us" title="English">English </a>|<a href="https://www.leonardscarf.com" hreflang="fa-ir" title="farsi"> Persian</a></span></h2>
</div>
</header>
<hr class="style-two">
<nav>
<ul itemscope itemtype="https://www.schema.org/SiteNavigationElement">
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com" title="صفحه اصلی">صفحه اصلی<br /> <small>شال و روسری</small></a></li>
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com/search/" title="جستجو">جستجو<br /> <small>تمام ارشیو</small></a></li>
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com/scarf/" title="روسری">روسری<br /> <small>جستجو روسری</small></a></li>
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com/shawl/" title="شال">شال<br /> <small>جستجو شال</small></a></li>
<?php if (!isset($_SESSION['usernamelogin'])) { ?>
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com/register/register" title="ثبت نام">ثبت نام<br /> <small>عضویت</small></a></li>
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com/register/loginuser" title="ورود">ورود<br /> <small>کاربر</small></a></li>
<?php } else { 	?>
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com/register/logout" title="خروج"><?php echo $_SESSION['usernamelogin']; ?><br /> <small>خروج</small></a></li>
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com/pricelist" title="لیست قیمت">لیست قیمت<br /> <small>شال و روسری</small></a></li>
<?php } ?>
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com/register/confirm-late" title="کد تایید">کد تایید<br /> <small>زمان ثبت نام</small></a></li>
<li itemprop="name"><a itemprop="url" href="https://www.leonardscarf.com/video.php" title="ویدئو">آرشیو ویدئو<br /> <small>شال و روسری</small></a></li>
</ul>
</nav>
<div id="wowslider-container1">
<div class="ws_images"><ul>
<li><img src="slide/data1/images/s2.jpg" alt="شال پاییزه" title="شال پاییزه" id="wows1_0"/></li>
<li><img src="slide/data1/images/s3.jpg" alt="روسری پاییزه" title="روسری پاییزه" id="wows1_1"/></li>
<li><img src="slide/data1/images/s4.jpg" alt="شال و روسری پاییزه" title="شال و روسری پاییزه" id="wows1_2"/></li>
</ul></div></div>
<script type="text/javascript" src="slide/engine1/wowslider.js"></script>
<script type="text/javascript" src="slide/engine1/script.js"></script>
<div class="submenu">
<ul><li>
<a href="#">روسری نخی</a>
<ul class="sub-submenu1">
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-11">ساده جناقی</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-12">لبه دانتل</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-13">طرح ال وی</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-14">عروسکی فندی</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-15">طرح نیمانی طهران</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-16">طرح ال وی دایره ای</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-17">طرح جغد</a></li>
<ul class="sub-submenu1">
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-18">طرح حاشیه گلیمی</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-19">طرح گوچی</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-20">طرح 2 حاشیه گلیمی</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-21">طرح براق گلدار</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-22">گل ریز خامه دوزی</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-23">خامه دوزی کلاه و دستکش</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-24">پاییزه حاشیه کارشده</a></li>
<ul class="sub-submenu1">
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-25">براق طرح خالدار</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-26">پاییزه براق</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-27">طرح ال وی کیفی</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-28">پاییزه طرح گلدار</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-29">روسری توییل ال وی</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-30">نخی طرح فانتزی</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-31">نخی طرح گل</a></li>
<ul class="sub-submenu1">
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-32">نخی طرح ترمه</a></li>
</ul></ul></ul></ul></li>
<li>
<a href="#">روسری ابریشم</a>
<ul class="sub-submenu1">
<li><a href="https://www.leonardscarf.com/view/scarf/silk/scarf-12">مامی طرح توپی و راه راه</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/silk/scarf-13">توییل دست دوز</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/silk/scarf-14">روسری ابریشم مامی</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/silk/scarf-15">روسری توئیل طرح شکوفه</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/silk/scarf-16">توئیل طرح کمربندی</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/silk/scarf-17">توئیل طرح ساعت</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/silk/scarf-18">توئیل طرح زنجیر</a></li>
<ul class="sub-submenu1">
<li><a href="https://www.leonardscarf.com/view/scarf/silk/scarf-19">مامی طرح گل</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/silk/scarf-20">توئیل طرح شکوفه</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/silk/scarf-21">ساتن ابریشم لئونارد</a></li>
</ul></ul></li>
<li>
<a href="#">روسری لنین</a>
<ul class="sub-submenu1">
<li><a href="https://www.leonardscarf.com/view/scarf/linen/scarf-1">لنین سایز 140</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/linen/scarf-2">لنین طرح ساده</a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/linen/scarf-3">لنین طرح لوییز ویتون</a></li>
</ul></li>
<li><a href="#">شال نخی</a>
<ul class="sub-submenu1">
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-20">ساده حاشیه آبرنگی</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-21">پاییزه پلیسه</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-22">پاییزه کبریتی</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-23">پاییزه چهار خانه موهر</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-24">پاییزه طرح هندسی</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-25">پشمی طرح زنجیر</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-26">پشمینه حاشیه گلدار</a></li>
<ul class="sub-submenu1">
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-27">موهر مربع هندسی</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-28">پاییزه اسنک دار</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-29">نخی اسنک دار</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-30">موهر طرح هاشور</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-31">موهر طرح موسچینو</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-32">کتان گل درشت</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-33">شال نخی طرح هاشور دار</a></li>
<ul class="sub-submenu1">
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-34">شال نخی 40 تکه</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-35">شال نخی طرح پروانه</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-36">شال نخی کتان منگوله</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-37">شال نخی کتان گل</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-38">شال نخی کتان ستاره</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-39">شال دستک قلاب بافی</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-40">شال بوکله اینگرین</a></li>
</ul></ul></ul></li>
<li><a href="#">شال لنین</a>
<ul class="sub-submenu1">
<li><a href="https://www.leonardscarf.com/view/shawl/linen/shawl-1">لنین خطی طیفی</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/linen/shawl-2">لنین طرح زبرا</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/linen/shawl-3">لب توری کار شده</a></li>
</ul></li>
<li><a href="#">شال ویسکوز</a>
<ul class="sub-submenu1">
<li><a href="https://www.leonardscarf.com/view/shawl/viscose/shawl-1">ویسکوز طرح جناقی</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/viscose/shawl-2">ویسکوز دو رنگ</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/viscose/shawl-3">ویسکوز نوار دوزی شده</a></li>
</ul></li>
<li><a href="#">شال پشمینه</a>
<ul class="sub-submenu1">
<li><a href="https://www.leonardscarf.com/view/shawl/woolen/shawl-1">پشمینه طرح گلیمی</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/woolen/shawl-2">پشمینه پاییزه گلدار</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/woolen/shawl-3">پشمینه پاییزه خالدار</a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/woolen/shawl-4">پشمینه موهر طرح ترمه</a></li>
</ul></li>
<li><a href="#">آرشیو</a>
<ul class="sub-submenu1">
<li><a href="https://www.leonardscarf.com/archive/cotton-scarf">روسری نخی</a></li>
<li><a href="https://www.leonardscarf.com/archive/silk-scarf">روسری ابریشم</a></li>
<li><a href="https://www.leonardscarf.com/archive/cotton-shawl">شال نخی</a></li>
<li><a href="https://www.leonardscarf.com/archive/melange-shawl">شال ملانژ</a></li>
</ul></li>
<li><a href="#">پشتیبانی</a>
<ul class="sub-submenu1">
<li><a href="https://www.leonardscarf.com/blog/">وبلاگ لئونارد</a></li>
<li><a href="https://www.leonardscarf.com/contactus">تماس با ما</a></li>
<li><a href="https://www.leonardscarf.com/about">درباره ما</a></li>
<li><a href="https://www.leonardscarf.com/complaints">شکایات</a></li>
<li><a href="https://www.leonardscarf.com/rules">قوانین و مقررات</a></li>
<li><a href="https://www.leonardscarf.com/app/">نرم افزار</a></li>
<li><a href="https://www.leonardscarf.com/sitemap">نقشه سایت</a></li>
</ul></li>
</ul>
</div>
<!--page_container-->
<h2 class="rules">توضیح مختصری از وبسایت
<strong>شال و روسری</strong> لئونارد</h2>
<h3 class="content">زیبائی و شیک پوشی دو موهبتی است که مکمل یکدیگر بوده
و در صد بسیاری از افراد در جوامع مختلف با توجه به فرهنگ و
رسومات همان جامعه سعی در بهتر به نظر رسیدن و در نتیجه
بیشتر دیده شدن و بیشتر مورد توجه قرار گرفتن دارند... طبیعی است
که همین بیشتر دیده شدن ها راه را برای پیشرفت نیز مهیا می کند
و زمینه ای برای رشد و ترقی خواهد شد.
شرکت<strong> شال و روسری لئونارد</strong>
همواره کوشیده که از طراحی تا تولید بالاترین کیفیت را به همراه زیباترین رنگ بندی با طرحهای روز دنیا
در اختیار شما بانوان محترم قرار دهد تا ضمن بهره مندی از محصولات بی نظیر این شرکت و در اختیار داشتن محصولی بروز و قابل رقابت با بزرگترین برندهای جهان هزینه کمتری بر شما هموطنان ارجمند تحمیل گردد </h3>
<h4 class="one" ><span>جدیدترین های شال و روسری</span></h4>
<div class="container">
<div class="main">
<div id="most-view" class="mi-slider">
<ul>
<li><a href="https://www.leonardscarf.com/view/scarf/silk/scarf-20"><img src="https://www.leonardscarf.com/images/scarf/silk/20/scarf-silk-20-black-200.jpg" alt="شال و روسری لئونارد" title="شال و روسری لئونارد"><h4>روسری ابریشم توئیل طرح شکوفه</h4></a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/silk/scarf-21"><img src="https://www.leonardscarf.com/images/scarf/silk/21/scarf-silk-21-white-200.jpg" alt="روسری ساتن ابریشم لئونارد" title="روسری ساتن ابریشم لئونارد"><h4>روسری ساتن ابریشم لئونارد</h4></a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-32"><img src="https://www.leonardscarf.com/images/scarf/cotton/32/scarf-cotton-32-cream-200.jpg" alt="روسری نخی طرح ترمه" title="روسری نخی طرح ترمه"><h4>روسری نخی طرح ترمه</h4></a></li>
<li><a href="https://www.leonardscarf.com/view/scarf/cotton/scarf-31"><img src="https://www.leonardscarf.com/images/scarf/cotton/31/scarf-cotton-31-darkblue-200.jpg" alt="روسری نخی طرح گل" title="روسری نخی طرح گل"><h4>روسری توئیل  ال وی</h4></a></li>
</ul>
<ul>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-40"><img src="https://www.leonardscarf.com/images/shawl/cotton/40/shawl-cotton-40-purple-200.jpg" alt="شال نخی بوکله اینگرین" title="شال نخی بوکله اینگرین"><h4>شال نخی بوکله اینگرین</h4></a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-39"><img src="https://www.leonardscarf.com/images/shawl/cotton/39/shawl-cotton-39-fili-200.jpg" alt="شال نخی دستک قلاب بافی" title="شال نخی دستک قلاب بافی"><h4>شال نخی دستک قلاب بافی</h4></a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/sheer/shawl-1"><img src="https://www.leonardscarf.com/images/shawl/sheer/1/shawl-sheer-1-pink-200.jpg" alt="شال حریر دو لایه مجلسی" title="شال حریر دو لایه مجلسی"><h4>شال حریر دو لایه مجلسی</h4></a></li>
<li><a href="https://www.leonardscarf.com/view/shawl/woolen/shawl-4"><img src="https://www.leonardscarf.com/images/shawl/woolen/4/shawl-woolen-4-pink-200.jpg" alt="شال پشمینه موهر طرح ترمه" title="شال پشمینه موهر طرح ترمه"><h4>شال پشمینه موهر طرح ترمه</h4></a></li>
</ul>
<nav>
<a href="">روسری</a>
<a href="">شال</a>
</nav>
</div>
</div>
</div><!-- /container -->
<h2 class="rules">پیشنهاد ما به شما برای خرید شال و روسری</h2>
<h3 class="content">شال یا روسری که قصد خریدش را دارید می بایست دارای کیفیت خوبی بوده تا ظاهر شمارا آراسته کند. جنس پارچه انتخاب شده باید بگونه ای باشد که مدت زمان معقولی عمر کند پس حتما قبل از خرید به بافت و جنس آن توجه کنید. لئونارد با توجه به تجربه ای درخشان و موفق در زمینه طراحی و تولید شال و روسری همواره سعی کرده است که تمامی محصولات خود را با بالاترین کیفیت مطلوب ,در اختیار شما مشتریان محترم قرار دهد از نشانه های شال یا روسری خوب می توان گفت که بهتر است جنس آن از هردوطرف کیفیت مطلوبی داشته باشد، هرچه بافت آن نرم و در عین حال مقاوم تر باشد ارزش آن بالاتر است. کسانی در انتخاب شال و روسری موفق ترند که هنگام خرید از شکل، فرم و رنگ پوست خود آگاهی داشته باشند و بدانند بر چه اساسی می بایست شال و روسری خود را انتخاب کنند. و این امر را لئونارد برای شما فراهم کرده است ,اگر قدی بلند و اندامی درشت دارید از روسری های تک رنگ و زیبای لئونارد (ترجیحا تیره) استفاده کنید تا شمارا لاغرتر نشان دهد. اگر کوتاه قد هستید و اندامی لاغر دارید بهتر است محور انتخاب روسری یا شال خود را برمبنای یک رنگ روشن و با ترکیبی از چند رنگ شاد که با رنگ اصلی  هارمونی داشته باشد, انتخاب بفرمائید.		</h3>
<h2 class="rules">سری جدید کالکشن تابستانه لئونارد</h2>
<div class="video">
<video poster="https://www.leonardscarf.com/video/poster/8.jpg" controls preload="none">
<source src="video/leonard-scarf-8.mp4" type="video/mp4">
<source src="video/leonard-scarf-8.ogg" type="video/ogg">
 مرورگر شما HTML5 را پشتیبانی نمیکند,لطفا مرورگر خود را بروز رسانی کنید.
</video>
</div>
<h2 class="rules">سیاست شرکت لئونارد</h2>
<h3 class="content">بطور کلی در حال حاضر اولویت اول مردم در جوامع پیشرفته , بهداشت و سلامتی جسم و روان می باشد و هرچه تولید بیشتر شود و کمیت افزایش یابد, کیفیت ازبین خواهد رفت, در همین راستا شرکت لئونارد رویه ای کاملا مستقل و متفاوت در تولیدات خود پیش گرفته و همواره بر این امر معتقد بوده  وهست که کیفیت بالای محصولات خود را فدای کمیت نکند.خاص بودن و بی همتا بودن محصولات لئونارد به دلیل کیفیت بالا و تکنولوژی مورد استفاده در تولید و نوع خدمت رسانی آن که بصورت اختصاصی و انحصاری در اختیار شرکت می باشد در کنار عدم قابلیت کپی برداری از محصولات لئونارد که تحت حمایت قوانین حق ثبت طرح صنعتی وزارت صنایع قرار دارد و تمهیدات دیگری که در همین زمینه بکار رفته, محصولات این شرکت را به کالایی فوق العاده و بی نظیر نه تنها در کشور بلکه در سطح منطقه تبدیل کرده است. گروه صنعتی لئونارد افتخار دارد که همواره بالاترین کیفیت محصولات را با تنوعی چشمگیر در سلایق خاص شما بانوان محترم ارائه دهد.</h3>
<script src="js/slider/jquery.catslider.js"></script>
<script>
$(function() {$( '#most-view' ).catslider();});
</script>
<footer class="footer-distributed" dir="rtl">
<hr class="style-one">
<div class="footer-left">
<h2>Leonard<span>Scarf</span></h2>
<p class="footer-links">
<a href="https://www.leonardscarf.com/index" title="صفحه اصلی">صفحه اصلی</a>&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/register/register" title="ثبت نام">ثبت نام</a>&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/register/loginuser" title="ورود به سایت">ورود به سایت</a>&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/contactus" title="تماس با ما">تماس با ما</a>&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/about" title="درباره ما">درباره ما</a>&nbsp;&nbsp;
</p>
<p class="footer-company-name">»Leonard Scarf &copy; 2015</p>
</div>
<div class="footer-center">
<div>
<i class="fa fa-map-marker"></i>
<p>ایران , تهران<span>15 خرداد بین الحرمین روبری مسجد بین الحرمین کوچه تکیه پلاک 3 (جنب سرای عزیزیان)</span></p>
</div>
<div>
<i class="fa fa-phone"></i>
<p dir="ltr">+982155555555</p>
</div>
<div>
<i class="fa fa-envelope"></i>
<p><a href="mailto:admin@leonardscarf.com.com">admin@leonardscarf.com</a></p>
</div>
</div>
<div class="footer-right">
<p class="footer-company-about">
<span><a href="https://www.leonardscarf.com/about" title="درباره شرکت لئونارد">درباره شرکت لئونارد</a></span>
لئونارد ارائه کننده برترین مدلهای شال و روسری
</p>
<div class="footer-icons">
<a href="https://www.facebook.com/leonardazin" title="Facebook"><i class="fa fa-facebook"></i></a>
<a href="https://telegram.me/joinchat/CEmNSjvmKui9SUKYbzrrqw" title="Telegram"><i class="fa fa-paper-plane"></i></a>
<a href="https://www.instagram.com/leonardscarf/?ref=badge" title="Instagram"><i class="fa fa-instagram"></i></a>
<a href="https://plus.google.com/118304422008766935997" title="Google plus"><i class="fa fa-google"></i></a>
</div>
</div>
</footer>
<div class="footer-up">
<hr class="style-two">
<div class="footer-center" dir="rtl">
<p class="footer-links">
<a href="https://www.leonardscarf.com/honours" title="افتخارات">افتخارات</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/rules" title="قوانین و مقررات">قوانین و مقررات</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/complaints" title="شکایات">شکایات</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/sitemap.php" title="نقشه سایت">نقشه سایت</a>&nbsp;&nbsp;&nbsp;&nbsp;
</p>
</div>
</div>
</body>
</html>