<?php
session_start();
?>
<!doctype html>
<html lang="fa" >
<head>
<meta charset='utf-8'>
<title>شال نخی گیپوردار لئونارد</title>
<link rel='icon' type='image/x-icon' href='https://www.leonardscarf.com/favicon.ico'>
<link rel="canonical" href="https://www.leonardscarf.com/view/shawl/cotton/shawl-15.php" />
<link rel="alternate" href="https://www.leonardscarf.com/view/shawl/cotton/shawl-15.php" hreflang="fa-ir" />
<link rel="prev" href="https://www.leonardscarf.com/view/shawl/cotton/shawl-14.php" />
<link rel="next" href="https://www.leonardscarf.com/view/shawl/cotton/shawl-16.php" />
<meta name='description' content='شال نخی گیپوردار لئونارد  دارای شش رنگ جذاب و پارچه ای با کیفیت و عالی, تحت لیسانس ایتالیا ,زیبایی و جذابیت همراه با شال و روسری لئونارد'>
<meta content='width=device-width, initial-scale=1.0' name='viewport'>
<meta name='keywords' content='شال ,روسری ,  شال و روسری , شال نخی'>
<meta name='author' content='mohsen bashirzadeh'>
<meta name="wot-verification" content="e07ff571dc2b59f09b95">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie" type="text/css">
<script type="text/javascript" src="../../../js/zoom/jquery.js"></script>
<link type="text/css" href="../../../css/zoom/cloud-zoom.css" rel="stylesheet" />
<script type="text/javascript" src="../../../js/zoom/cloud-zoom.1.0.2.min.js"></script>
<!-- #region Jssor Slider Begin --><!-- Generated by Jssor Slider Maker. --><!-- This is deep minimized demo, it works alone, it doesn't depend on any javascript library. --><script>(function(h,f,c,j,d,l,k){/*! Jssor */
new(function(){});var e={sd:function(a){return-c.cos(a*c.PI)/2+.5},xd:function(a){return a},zd:function(a){return-a*(a-2)}};var b=new function(){var g=this,Ab=/\S+/g,F=1,yb=2,fb=3,eb=4,jb=5,G,r=0,i=0,s=0,X=0,z=0,I=navigator,ob=I.appName,o=I.userAgent,p=parseFloat;function Ib(){if(!G){G={Wd:"ontouchstart"in h||"createTouch"in f};var a;if(I.pointerEnabled||(a=I.msPointerEnabled))G.Yc=a?"msTouchAction":"touchAction"}return G}function v(j){if(!r){r=-1;if(ob=="Microsoft Internet Explorer"&&!!h.attachEvent&&!!h.ActiveXObject){var e=o.indexOf("MSIE");r=F;s=p(o.substring(e+5,o.indexOf(";",e)));/*@cc_on X=@_jscript_version@*/;i=f.documentMode||s}else if(ob=="Netscape"&&!!h.addEventListener){var d=o.indexOf("Firefox"),b=o.indexOf("Safari"),g=o.indexOf("Chrome"),c=o.indexOf("AppleWebKit");if(d>=0){r=yb;i=p(o.substring(d+8))}else if(b>=0){var k=o.substring(0,b).lastIndexOf("/");r=g>=0?eb:fb;i=p(o.substring(k+1,b))}else{var a=/Trident\/.*rv:([0-9]{1,}[\.0-9]{0,})/i.exec(o);if(a){r=F;i=s=p(a[1])}}if(c>=0)z=p(o.substring(c+12))}else{var a=/(opera)(?:.*version|)[ \/]([\w.]+)/i.exec(o);if(a){r=jb;i=p(a[2])}}}return j==r}function q(){return v(F)}function Q(){return q()&&(i<6||f.compatMode=="BackCompat")}function db(){return v(fb)}function ib(){return v(jb)}function vb(){return db()&&z>534&&z<535}function J(){v();return z>537||i>42||r==F&&i>=11}function O(){return q()&&i<9}function wb(a){var b,c;return function(f){if(!b){b=d;var e=a.substr(0,1).toUpperCase()+a.substr(1);n([a].concat(["WebKit","ms","Moz","O","webkit"]),function(g,d){var b=a;if(d)b=g+e;if(f.style[b]!=k)return c=b})}return c}}function ub(b){var a;return function(c){a=a||wb(b)(c)||b;return a}}var K=ub("transform");function nb(a){return{}.toString.call(a)}var kb={};n(["Boolean","Number","String","Function","Array","Date","RegExp","Object"],function(a){kb["[object "+a+"]"]=a.toLowerCase()});function n(b,d){var a,c;if(nb(b)=="[object Array]"){for(a=0;a<b.length;a++)if(c=d(b[a],a,b))return c}else for(a in b)if(c=d(b[a],a,b))return c}function C(a){return a==j?String(a):kb[nb(a)]||"object"}function lb(a){for(var b in a)return d}function A(a){try{return C(a)=="object"&&!a.nodeType&&a!=a.window&&(!a.constructor||{}.hasOwnProperty.call(a.constructor.prototype,"isPrototypeOf"))}catch(b){}}function u(a,b){return{x:a,y:b}}function rb(b,a){setTimeout(b,a||0)}function H(b,d,c){var a=!b||b=="inherit"?"":b;n(d,function(c){var b=c.exec(a);if(b){var d=a.substr(0,b.index),e=a.substr(b.index+b[0].length+1,a.length-1);a=d+e}});a=c+(!a.indexOf(" ")?"":" ")+a;return a}function tb(b,a){if(i<9)b.style.filter=a}g.Td=Ib;g.ad=q;g.ze=db;g.Sd=J;g.Hc=O;wb("transform");g.mc=function(){return i};g.kc=rb;function Y(a){a.constructor===Y.caller&&a.oc&&a.oc.apply(a,Y.caller.arguments)}g.oc=Y;g.vb=function(a){if(g.Zd(a))a=f.getElementById(a);return a};function t(a){return a||h.event}g.pc=t;g.Gb=function(b){b=t(b);var a=b.target||b.srcElement||f;if(a.nodeType==3)a=g.jc(a);return a};g.gc=function(a){a=t(a);return{x:a.pageX||a.clientX||0,y:a.pageY||a.clientY||0}};function D(c,d,a){if(a!==k)c.style[d]=a==k?"":a;else{var b=c.currentStyle||c.style;a=b[d];if(a==""&&h.getComputedStyle){b=c.ownerDocument.defaultView.getComputedStyle(c,j);b&&(a=b.getPropertyValue(d)||b[d])}return a}}function ab(b,c,a,d){if(a!==k){if(a==j)a="";else d&&(a+="px");D(b,c,a)}else return p(D(b,c))}function m(c,a){var d=a?ab:D,b;if(a&4)b=ub(c);return function(e,f){return d(e,b?b(e):c,f,a&2)}}function Db(b){if(q()&&s<9){var a=/opacity=([^)]*)/.exec(b.style.filter||"");return a?p(a[1])/100:1}else return p(b.style.opacity||"1")}function Fb(b,a,f){if(q()&&s<9){var h=b.style.filter||"",i=new RegExp(/[\s]*alpha\([^\)]*\)/g),e=c.round(100*a),d="";if(e<100||f)d="alpha(opacity="+e+") ";var g=H(h,[i],d);tb(b,g)}else b.style.opacity=a==1?"":c.round(a*100)/100}var L={Q:["rotate"],F:["rotateX"],E:["rotateY"],tb:["skewX"],sb:["skewY"]};if(!J())L=B(L,{k:["scaleX",2],l:["scaleY",2],D:["translateZ",1]});function M(d,a){var c="";if(a){if(q()&&i&&i<10){delete a.F;delete a.E;delete a.D}b.e(a,function(d,b){var a=L[b];if(a){var e=a[1]||0;if(N[b]!=d)c+=" "+a[0]+"("+d+(["deg","px",""])[e]+")"}});if(J()){if(a.V||a.bb||a.D)c+=" translate3d("+(a.V||0)+"px,"+(a.bb||0)+"px,"+(a.D||0)+"px)";if(a.k==k)a.k=1;if(a.l==k)a.l=1;if(a.k!=1||a.l!=1)c+=" scale3d("+a.k+", "+a.l+", 1)"}}d.style[K(d)]=c}g.Fc=m("transformOrigin",4);g.Rd=m("backfaceVisibility",4);g.Qd=m("transformStyle",4);g.Pd=m("perspective",6);g.me=m("perspectiveOrigin",4);g.we=function(a,b){if(q()&&s<9||s<10&&Q())a.style.zoom=b==1?"":b;else{var c=K(a),f="scale("+b+")",e=a.style[c],g=new RegExp(/[\s]*scale\(.*?\)/g),d=H(e,[g],f);a.style[c]=d}};g.Dc=function(b,a){return function(c){c=t(c);var e=c.type,d=c.relatedTarget||(e=="mouseout"?c.toElement:c.fromElement);(!d||d!==a&&!g.Fe(a,d))&&b(c)}};g.a=function(a,d,b,c){a=g.vb(a);if(a.addEventListener){d=="mousewheel"&&a.addEventListener("DOMMouseScroll",b,c);a.addEventListener(d,b,c)}else if(a.attachEvent){a.attachEvent("on"+d,b);c&&a.setCapture&&a.setCapture()}};g.A=function(a,c,d,b){a=g.vb(a);if(a.removeEventListener){c=="mousewheel"&&a.removeEventListener("DOMMouseScroll",d,b);a.removeEventListener(c,d,b)}else if(a.detachEvent){a.detachEvent("on"+c,d);b&&a.releaseCapture&&a.releaseCapture()}};g.yb=function(a){a=t(a);a.preventDefault&&a.preventDefault();a.cancel=d;a.returnValue=l};g.Ae=function(a){a=t(a);a.stopPropagation&&a.stopPropagation();a.cancelBubble=d};g.X=function(d,c){var a=[].slice.call(arguments,2),b=function(){var b=a.concat([].slice.call(arguments,0));return c.apply(d,b)};return b};g.He=function(a,b){if(b==k)return a.textContent||a.innerText;var c=f.createTextNode(b);g.Mb(a);a.appendChild(c)};g.pb=function(d,c){for(var b=[],a=d.firstChild;a;a=a.nextSibling)(c||a.nodeType==1)&&b.push(a);return b};function mb(a,c,e,b){b=b||"u";for(a=a?a.firstChild:j;a;a=a.nextSibling)if(a.nodeType==1){if(U(a,b)==c)return a;if(!e){var d=mb(a,c,e,b);if(d)return d}}}g.u=mb;function S(a,d,f,b){b=b||"u";var c=[];for(a=a?a.firstChild:j;a;a=a.nextSibling)if(a.nodeType==1){U(a,b)==d&&c.push(a);if(!f){var e=S(a,d,f,b);if(e.length)c=c.concat(e)}}return c}g.pe=S;function gb(a,c,d){for(a=a?a.firstChild:j;a;a=a.nextSibling)if(a.nodeType==1){if(a.tagName==c)return a;if(!d){var b=gb(a,c,d);if(b)return b}}}g.oe=gb;function B(){var e=arguments,d,c,b,a,g=1&e[0],f=1+g;d=e[f-1]||{};for(;f<e.length;f++)if(c=e[f])for(b in c){a=c[b];if(a!==k){a=c[b];var h=d[b];d[b]=g&&(A(h)||A(a))?B(g,{},h,a):a}}return d}g.kb=B;function Z(f,g){var d={},c,a,b;for(c in f){a=f[c];b=g[c];if(a!==b){var e;if(A(a)&&A(b)){a=Z(a,b);e=!lb(a)}!e&&(d[c]=a)}}return d}g.wc=function(a){return C(a)=="function"};g.Zd=function(a){return C(a)=="string"};g.nd=function(a){return!isNaN(p(a))&&isFinite(a)};g.e=n;function R(a){return f.createElement(a)}g.nb=function(){return R("DIV")};g.uc=function(){};function V(b,c,a){if(a==k)return b.getAttribute(c);b.setAttribute(c,a)}function U(a,b){return V(a,b)||V(a,"data-"+b)}g.v=V;g.g=U;function x(b,a){if(a==k)return b.className;b.className=a}g.sc=x;function qb(b){var a={};n(b,function(b){a[b]=b});return a}function sb(b,a){return b.match(a||Ab)}function P(b,a){return qb(sb(b||"",a))}g.fd=sb;function bb(b,c){var a="";n(c,function(c){a&&(a+=b);a+=c});return a}function E(a,c,b){x(a,bb(" ",B(Z(P(x(a)),P(c)),P(b))))}g.jc=function(a){return a.parentNode};g.B=function(a){g.C(a,"none")};g.P=function(a,b){g.C(a,b?"none":"")};g.Ld=function(b,a){b.removeAttribute(a)};g.Kd=function(){return q()&&i<10};g.Jd=function(d,a){if(a)d.style.clip="rect("+c.round(a.i||a.o||0)+"px "+c.round(a.r)+"px "+c.round(a.q)+"px "+c.round(a.j||a.p||0)+"px)";else if(a!==k){var g=d.style.cssText,f=[new RegExp(/[\s]*clip: rect\(.*?\)[;]?/i),new RegExp(/[\s]*cliptop: .*?[;]?/i),new RegExp(/[\s]*clipright: .*?[;]?/i),new RegExp(/[\s]*clipbottom: .*?[;]?/i),new RegExp(/[\s]*clipleft: .*?[;]?/i)],e=H(g,f,"");b.Db(d,e)}};g.H=function(){return+new Date};g.I=function(b,a){b.appendChild(a)};g.Ob=function(b,a,c){(c||a.parentNode).insertBefore(b,a)};g.ic=function(b,a){a=a||b.parentNode;a&&a.removeChild(b)};g.Bd=function(a,b){n(a,function(a){g.ic(a,b)})};g.Mb=function(a){g.Bd(g.pb(a,d),a)};g.Ad=function(a,b){var c=g.jc(a);b&1&&g.J(a,(g.m(c)-g.m(a))/2);b&2&&g.K(a,(g.n(c)-g.n(a))/2)};g.wd=function(b,a){return parseInt(b,a||10)};g.vd=p;g.Fe=function(b,a){var c=f.body;while(a&&b!==a&&c!==a)try{a=a.parentNode}catch(d){return l}return b===a};function W(d,c,b){var a=d.cloneNode(!c);!b&&g.Ld(a,"id");return a}g.hb=W;g.gb=function(e,f){var a=new Image;function b(e,d){g.A(a,"load",b);g.A(a,"abort",c);g.A(a,"error",c);f&&f(a,d)}function c(a){b(a,d)}if(ib()&&i<11.6||!e)b(!e);else{g.a(a,"load",b);g.a(a,"abort",c);g.a(a,"error",c);a.src=e}};g.ud=function(d,a,e){var c=d.length+1;function b(b){c--;if(a&&b&&b.src==a.src)a=b;!c&&e&&e(a)}n(d,function(a){g.gb(a.src,b)});b()};function Gb(a){var l=this,p="",r=["av","pv","ds","dn"],e=[],q,j=0,h=0,d=0;function i(){E(a,q,e[d||j||h&2||h]);b.L(a,"pointer-events",d?"none":"")}function c(){j=0;i();g.A(f,"mouseup",c);g.A(f,"touchend",c);g.A(f,"touchcancel",c)}function o(a){if(d)g.yb(a);else{j=4;i();g.a(f,"mouseup",c);g.a(f,"touchend",c);g.a(f,"touchcancel",c)}}l.nc=function(a){if(a===k)return!d;d=a?0:3;i()};l.M=a=g.vb(a);var m=b.fd(x(a));if(m)p=m.shift();n(r,function(a){e.push(p+a)});q=bb(" ",e);e.unshift("");g.a(a,"mousedown",o);g.a(a,"touchstart",o)}g.Ic=function(a){return new Gb(a)};g.L=D;g.qb=m("overflow");g.K=m("top",2);g.J=m("left",2);g.m=m("width",2);g.n=m("height",2);g.Dd=m("marginLeft",2);g.Ed=m("marginTop",2);g.z=m("position");g.C=m("display");g.s=m("zIndex",1);g.Zb=function(b,a,c){if(a!=k)Fb(b,a,c);else return Db(b)};g.Db=function(a,b){if(b!=k)a.style.cssText=b;else return a.style.cssText};var T={jb:g.Zb,i:g.K,j:g.J,Fb:g.m,zb:g.n,mb:g.z,Se:g.C,db:g.s};function w(f,l){var e=O(),b=J(),d=vb(),h=K(f);function i(b,d,a){var e=b.T(u(-d/2,-a/2)),f=b.T(u(d/2,-a/2)),g=b.T(u(d/2,a/2)),h=b.T(u(-d/2,a/2));b.T(u(300,300));return u(c.min(e.x,f.x,g.x,h.x)+d/2,c.min(e.y,f.y,g.y,h.y)+a/2)}function a(d,a){a=a||{};var f=a.D||0,l=(a.F||0)%360,m=(a.E||0)%360,o=(a.Q||0)%360,p=a.Re;if(e){f=0;l=0;m=0;p=0}var c=new Cb(a.V,a.bb,f);c.F(l);c.E(m);c.gd(o);c.kd(a.tb,a.sb);c.vc(a.k,a.l,p);if(b){c.ib(a.p,a.o);d.style[h]=c.md()}else if(!X||X<9){var j="";if(o||a.k!=k&&a.k!=1||a.l!=k&&a.l!=1){var n=i(c,a.U,a.Z);g.Ed(d,n.y);g.Dd(d,n.x);j=c.Nd()}var r=d.style.filter,s=new RegExp(/[\s]*progid:DXImageTransform\.Microsoft\.Matrix\([^\)]*\)/g),q=H(r,[s],j);tb(d,q)}}w=function(e,c){c=c||{};var h=c.p,i=c.o,f;n(T,function(a,b){f=c[b];f!==k&&a(e,f)});g.Jd(e,c.c);if(!b){h!=k&&g.J(e,(c.yc||0)+h);i!=k&&g.K(e,(c.zc||0)+i)}if(c.te)if(d)rb(g.X(j,M,e,c));else a(e,c)};g.Ab=M;if(d)g.Ab=w;if(e)g.Ab=a;else if(!b)a=M;g.O=w;w(f,l)}g.Ab=w;g.O=w;function Cb(i,l,p){var d=this,b=[1,0,0,0,0,1,0,0,0,0,1,0,i||0,l||0,p||0,1],h=c.sin,g=c.cos,m=c.tan;function f(a){return a*c.PI/180}function o(a,b){return{x:a,y:b}}function n(c,e,l,m,o,r,t,u,w,z,A,C,E,b,f,k,a,g,i,n,p,q,s,v,x,y,B,D,F,d,h,j){return[c*a+e*p+l*x+m*F,c*g+e*q+l*y+m*d,c*i+e*s+l*B+m*h,c*n+e*v+l*D+m*j,o*a+r*p+t*x+u*F,o*g+r*q+t*y+u*d,o*i+r*s+t*B+u*h,o*n+r*v+t*D+u*j,w*a+z*p+A*x+C*F,w*g+z*q+A*y+C*d,w*i+z*s+A*B+C*h,w*n+z*v+A*D+C*j,E*a+b*p+f*x+k*F,E*g+b*q+f*y+k*d,E*i+b*s+f*B+k*h,E*n+b*v+f*D+k*j]}function e(c,a){return n.apply(j,(a||b).concat(c))}d.vc=function(a,c,d){if(a==k)a=1;if(c==k)c=1;if(d==k)d=1;if(a!=1||c!=1||d!=1)b=e([a,0,0,0,0,c,0,0,0,0,d,0,0,0,0,1])};d.ib=function(a,c,d){b[12]+=a||0;b[13]+=c||0;b[14]+=d||0};d.F=function(c){if(c){a=f(c);var d=g(a),i=h(a);b=e([1,0,0,0,0,d,i,0,0,-i,d,0,0,0,0,1])}};d.E=function(c){if(c){a=f(c);var d=g(a),i=h(a);b=e([d,0,-i,0,0,1,0,0,i,0,d,0,0,0,0,1])}};d.gd=function(c){if(c){a=f(c);var d=g(a),i=h(a);b=e([d,i,0,0,-i,d,0,0,0,0,1,0,0,0,0,1])}};d.kd=function(a,c){if(a||c){i=f(a);l=f(c);b=e([1,m(l),0,0,m(i),1,0,0,0,0,1,0,0,0,0,1])}};d.T=function(c){var a=e(b,[1,0,0,0,0,1,0,0,0,0,1,0,c.x,c.y,0,1]);return o(a[12],a[13])};d.md=function(){return"matrix3d("+b.join(",")+")"};d.Nd=function(){return"progid:DXImageTransform.Microsoft.Matrix(M11="+b[0]+", M12="+b[4]+", M21="+b[1]+", M22="+b[5]+", SizingMethod='auto expand')"}}new function(){var a=this;function b(d,g){for(var j=d[0].length,i=d.length,h=g[0].length,f=[],c=0;c<i;c++)for(var k=f[c]=[],b=0;b<h;b++){for(var e=0,a=0;a<j;a++)e+=d[c][a]*g[a][b];k[b]=e}return f}a.k=function(b,c){return a.Ec(b,c,0)};a.l=function(b,c){return a.Ec(b,0,c)};a.Ec=function(a,c,d){return b(a,[[c,0],[0,d]])};a.T=function(d,c){var a=b(d,[[c.x],[c.y]]);return u(a[0][0],a[1][0])}};var N={yc:0,zc:0,p:0,o:0,S:1,k:1,l:1,Q:0,F:0,E:0,V:0,bb:0,D:0,tb:0,sb:0};g.Od=function(a){var c=a||{};if(a)if(b.wc(a))c={Sb:c};else if(b.wc(a.c))c.c={Sb:a.c};return c};g.je=function(l,m,x,q,z,A,n){var a=m;if(l){a={};for(var g in m){var B=A[g]||1,w=z[g]||[0,1],f=(x-w[0])/w[1];f=c.min(c.max(f,0),1);f=f*B;var u=c.floor(f);if(f!=u)f-=u;var h=q.Sb||e.sd,i,C=l[g],o=m[g];if(b.nd(o)){h=q[g]||h;var y=h(f);i=C+o*y}else{i=b.kb({xb:{}},l[g]);var v=q[g]||{};b.e(o.xb||o,function(d,a){h=v[a]||v.Sb||h;var c=h(f),b=d*c;i.xb[a]=b;i[a]+=b})}a[g]=i}var t=b.e(m,function(b,a){return N[a]!=k});t&&b.e(N,function(c,b){if(a[b]==k&&l[b]!==k)a[b]=l[b]});if(t){if(a.S)a.k=a.l=a.S;a.U=n.U;a.Z=n.Z;a.te=d}}if(m.c&&n.ib){var p=a.c.xb,s=(p.i||0)+(p.q||0),r=(p.j||0)+(p.r||0);a.j=(a.j||0)+r;a.i=(a.i||0)+s;a.c.j-=r;a.c.r-=r;a.c.i-=s;a.c.q-=s}if(a.c&&b.Kd()&&!a.c.i&&!a.c.j&&!a.c.o&&!a.c.p&&a.c.r==n.U&&a.c.q==n.Z)a.c=j;return a}};function n(){var a=this,d=[];function i(a,b){d.push({ec:a,cc:b})}function g(a,c){b.e(d,function(b,e){b.ec==a&&b.cc===c&&d.splice(e,1)})}a.lb=a.addEventListener=i;a.removeEventListener=g;a.f=function(a){var c=[].slice.call(arguments,1);b.e(d,function(b){b.ec==a&&b.cc.apply(h,c)})}}var m=function(z,C,i,J,M,L){z=z||0;var a=this,q,n,o,u,A=0,G,H,F,B,y=0,g=0,m=0,D,k,f,e,p,w=[],x;function O(a){f+=a;e+=a;k+=a;g+=a;m+=a;y+=a}function t(o){var h=o;if(p&&(h>=e||h<=f))h=((h-f)%p+p)%p+f;if(!D||u||g!=h){var j=c.min(h,e);j=c.max(j,f);if(!D||u||j!=m){if(L){var l=(j-k)/(C||1);if(i.Hd)l=1-l;var n=b.je(M,L,l,G,F,H,i);if(x)b.e(n,function(b,a){x[a]&&x[a](J,b)});else b.O(J,n)}a.dc(m-k,j-k);m=j;b.e(w,function(b,c){var a=o<g?w[w.length-c-1]:b;a.N(m-y)});var r=g,q=m;g=h;D=d;a.Bb(r,q)}}}function E(a,b,d){b&&a.Nb(e);if(!d){f=c.min(f,a.Uc()+y);e=c.max(e,a.Pb()+y)}w.push(a)}var r=h.requestAnimationFrame||h.webkitRequestAnimationFrame||h.mozRequestAnimationFrame||h.msRequestAnimationFrame;if(b.ze()&&b.mc()<7)r=j;r=r||function(a){b.kc(a,i.Tc)};function I(){if(q){var d=b.H(),e=c.min(d-A,i.Nc),a=g+e*o;A=d;if(a*o>=n*o)a=n;t(a);if(!u&&a*o>=n*o)K(B);else r(I)}}function s(h,i,j){if(!q){q=d;u=j;B=i;h=c.max(h,f);h=c.min(h,e);n=h;o=n<g?-1:1;a.Pc();A=b.H();r(I)}}function K(b){if(q){u=q=B=l;a.Rc();b&&b()}}a.Xc=function(a,b,c){s(a?g+a:e,b,c)};a.Zc=s;a.R=K;a.Vd=function(a){s(a)};a.G=function(){return g};a.ed=function(){return n};a.fb=function(){return m};a.N=t;a.ib=function(a){t(g+a)};a.Kc=function(){return q};a.ce=function(a){p=a};a.Nb=O;a.fc=function(a,b){E(a,0,b)};a.Hb=function(a){E(a,1)};a.Uc=function(){return f};a.Pb=function(){return e};a.Bb=a.Pc=a.Rc=a.dc=b.uc;a.Xb=b.H();i=b.kb({Tc:16,Nc:50},i);p=i.xc;x=i.yd;f=k=z;e=z+C;H=i.td||{};F=i.fe||{};G=b.Od(i.eb)};new(function(){});var i=function(p,fc){var g=this;function Bc(){var a=this;m.call(a,-1e8,2e8);a.be=function(){var b=a.fb(),d=c.floor(b),f=t(d),e=b-c.floor(b);return{W:f,Ie:d,mb:e}};a.Bb=function(b,a){var e=c.floor(a);if(e!=a&&a>b)e++;Tb(e,d);g.f(i.le,t(a),t(b),a,b)}}function Ac(){var a=this;m.call(a,0,0,{xc:r});b.e(C,function(b){D&1&&b.ce(r);a.Hb(b);b.Nb(kb/bc)})}function zc(){var a=this,b=Ub.M;m.call(a,-1,2,{eb:e.xd,yd:{mb:Zb},xc:r},b,{mb:1},{mb:-2});a.Jb=b}function mc(o,n){var b=this,e,f,h,k,c;m.call(b,-1e8,2e8,{Nc:100});b.Pc=function(){M=d;R=j;g.f(i.ie,t(w.G()),w.G())};b.Rc=function(){M=l;k=l;var a=w.be();g.f(i.he,t(w.G()),w.G());!a.mb&&Dc(a.Ie,s)};b.Bb=function(i,g){var b;if(k)b=c;else{b=f;if(h){var d=g/h;b=a.ge(d)*(f-e)+e}}w.N(b)};b.ub=function(a,d,c,g){e=a;f=d;h=c;w.N(a);b.N(0);b.Zc(c,g)};b.ee=function(a){k=d;c=a;b.Xc(a,j,d)};b.de=function(a){c=a};w=new Bc;w.fc(o);w.fc(n)}function oc(){var c=this,a=Xb();b.s(a,0);b.L(a,"pointerEvents","none");c.M=a;c.wb=function(){b.B(a);b.Mb(a)}}function xc(o,f){var e=this,q,L,v,k,y=[],x,B,W,G,Q,F,h,w,p;m.call(e,-u,u+1,{});function E(a){q&&q.Lc();T(o,a,0);F=d;q=new I.ab(o,I,b.vd(b.g(o,"idle"))||lc);q.N(0)}function Z(){q.Xb<I.Xb&&E()}function M(p,r,o){if(!G){G=d;if(k&&o){var h=o.width,c=o.height,n=h,m=c;if(h&&c&&a.cb){if(a.cb&3&&(!(a.cb&4)||h>K||c>J)){var j=l,q=K/J*c/h;if(a.cb&1)j=q>1;else if(a.cb&2)j=q<1;n=j?h*J/c:K;m=j?J:c*K/h}b.m(k,n);b.n(k,m);b.K(k,(J-m)/2);b.J(k,(K-n)/2)}b.z(k,"absolute");g.f(i.ae,f)}}b.B(r);p&&p(e)}function Y(b,c,d,g){if(g==R&&s==f&&N)if(!Cc){var a=t(b);A.hd(a,f,c,e,d);c.Yd();U.Nb(a-U.Uc()-1);U.N(a);z.ub(b,b,0)}}function bb(b){if(b==R&&s==f){if(!h){var a=j;if(A)if(A.W==f)a=A.De();else A.wb();Z();h=new vc(o,f,a,q);h.Mc(p)}!h.Kc()&&h.Kb()}}function S(d,g,l){if(d==f){if(d!=g)C[g]&&C[g].Xd();else!l&&h&&h.Ud();p&&p.nc();var m=R=b.H();e.gb(b.X(j,bb,m))}else{var k=c.min(f,d),i=c.max(f,d),o=c.min(i-k,k+r-i),n=u+a.ne-1;(!Q||o<=n)&&e.gb()}}function db(){if(s==f&&h){h.R();p&&p.Ge();p&&p.Ee();h.dd()}}function eb(){s==f&&h&&h.R()}function ab(a){!P&&g.f(i.Ce,f,a)}function O(){p=w.pInstance;h&&h.Mc(p)}e.gb=function(c,a){a=a||v;if(y.length&&!G){b.P(a);if(!W){W=d;g.f(i.Be,f);b.e(y,function(a){if(!b.v(a,"src")){a.src=b.g(a,"src2");b.C(a,a["display-origin"])}})}b.ud(y,k,b.X(j,M,c,a))}else M(c,a)};e.xe=function(){var h=f;if(a.Ub<0)h-=r;var d=h+a.Ub*tc;if(D&2)d=t(d);if(!(D&1)&&!ib)d=c.max(0,c.min(d,r-u));if(d!=f){if(A){var e=A.ke(r);if(e){var i=R=b.H(),g=C[t(d)];return g.gb(b.X(j,Y,d,g,e,i),v)}}cb(d)}};e.ac=function(){S(f,f,d)};e.Xd=function(){p&&p.Ge();p&&p.Ee();e.Jc();h&&h.ue();h=j;E()};e.Yd=function(){b.B(o)};e.Jc=function(){b.P(o)};e.se=function(){p&&p.nc()};function T(a,c,e){if(b.v(a,"jssor-slider"))return;if(!F){if(a.tagName=="IMG"){y.push(a);if(!b.v(a,"src")){Q=d;a["display-origin"]=b.C(a);b.B(a)}}b.Hc()&&b.s(a,(b.s(a)||0)+1)}var f=b.pb(a);b.e(f,function(f){var h=f.tagName,i=b.g(f,"u");if(i=="player"&&!w){w=f;if(w.pInstance)O();else b.a(w,"dataavailable",O)}if(i=="caption"){if(c){b.Fc(f,b.g(f,"to"));b.Rd(f,b.g(f,"bf"));b.g(f,"3d")&&b.Qd(f,"preserve-3d")}else if(!b.ad()){var g=b.hb(f,l,d);b.Ob(g,f,a);b.ic(f,a);f=g;c=d}}else if(!F&&!e&&!k){if(h=="A"){if(b.g(f,"u")=="image")k=b.oe(f,"IMG");else k=b.u(f,"image",d);if(k){x=f;b.C(x,"block");b.O(x,V);B=b.hb(x,d);b.z(x,"relative");b.Zb(B,0);b.L(B,"backgroundColor","#000")}}else if(h=="IMG"&&b.g(f,"u")=="image")k=f;if(k){k.border=0;b.O(k,V)}}T(f,c,e+1)})}e.dc=function(c,b){var a=u-b;Zb(L,a)};e.W=f;n.call(e);b.Pd(o,b.g(o,"p"));b.me(o,b.g(o,"po"));var H=b.u(o,"thumb",d);if(H){b.hb(H);b.B(H)}b.P(o);v=b.hb(gb);b.s(v,1e3);b.a(o,"click",ab);E(d);e.ve=k;e.Vc=B;e.Jb=L=o;b.I(L,v);g.lb(203,S);g.lb(28,eb);g.lb(24,db)}function vc(y,f,p,q){var a=this,n=0,u=0,h,j,e,c,k,t,r,o=C[f];m.call(a,0,0);function v(){b.Mb(L);cc&&k&&o.Vc&&b.I(L,o.Vc);b.P(L,!k&&o.ve)}function w(){a.Kb()}function x(b){r=b;a.R();a.Kb()}a.Kb=function(){var b=a.fb();if(!B&&!M&&!r&&s==f){if(!b){if(h&&!k){k=d;a.dd(d);g.f(i.qe,f,n,u,h,c)}v()}var l,p=i.bd;if(b!=c)if(b==e)l=c;else if(b==j)l=e;else if(!b)l=j;else l=a.ed();g.f(p,f,b,n,j,e,c);var m=N&&(!E||F);if(b==c)(e!=c&&!(E&12)||m)&&o.xe();else(m||b!=e)&&a.Zc(l,w)}};a.Ud=function(){e==c&&e==a.fb()&&a.N(j)};a.ue=function(){A&&A.W==f&&A.wb();var b=a.fb();b<c&&g.f(i.bd,f,-b-1,n,j,e,c)};a.dd=function(a){p&&b.qb(lb,a&&p.hc.Je?"":"hidden")};a.dc=function(b,a){if(k&&a>=h){k=l;v();o.Jc();A.wb();g.f(i.Id,f,n,u,h,c)}g.f(i.ld,f,a,n,j,e,c)};a.Mc=function(a){if(a&&!t){t=a;a.lb($JssorPlayer$.Cd,x)}};p&&a.Hb(p);h=a.Pb();a.Hb(q);j=h+q.Sc;e=h+q.Qc;c=a.Pb()}function Kb(a,c,d){b.J(a,c);b.K(a,d)}function Zb(c,b){var a=x>0?x:fb,d=zb*b*(a&1),e=Ab*b*(a>>1&1);Kb(c,d,e)}function Pb(){qb=M;Ib=z.ed();G=w.G()}function gc(){Pb();if(B||!F&&E&12){z.R();g.f(i.id)}}function ec(f){if(!B&&(F||!(E&12))&&!z.Kc()){var d=w.G(),b=c.ceil(G);if(f&&c.abs(H)>=a.Oc){b=c.ceil(d);b+=jb}if(!(D&1))b=c.min(r-u,c.max(b,0));var e=c.abs(b-d);e=1-c.pow(1-e,5);if(!P&&qb)z.Vd(Ib);else if(d==b){tb.se();tb.ac()}else z.ub(d,b,e*Vb)}}function Hb(a){!b.g(b.Gb(a),"nodrag")&&b.yb(a)}function rc(a){Yb(a,1)}function Yb(a,c){a=b.pc(a);var k=b.Gb(a);if(!O&&!b.g(k,"nodrag")&&sc()&&(!c||a.touches.length==1)){B=d;yb=l;R=j;b.a(f,c?"touchmove":"mousemove",Bb);b.H();P=0;gc();if(!qb)x=0;if(c){var h=a.touches[0];ub=h.clientX;vb=h.clientY}else{var e=b.gc(a);ub=e.x;vb=e.y}H=0;hb=0;jb=0;g.f(i.jd,t(G),G,a)}}function Bb(e){if(B){e=b.pc(e);var f;if(e.type!="mousemove"){var l=e.touches[0];f={x:l.clientX,y:l.clientY}}else f=b.gc(e);if(f){var j=f.x-ub,k=f.y-vb;if(c.floor(G)!=G)x=x||fb&O;if((j||k)&&!x){if(O==3)if(c.abs(k)>c.abs(j))x=2;else x=1;else x=O;if(ob&&x==1&&c.abs(k)-c.abs(j)>3)yb=d}if(x){var a=k,i=Ab;if(x==1){a=j;i=zb}if(!(D&1)){if(a>0){var g=i*s,h=a-g;if(h>0)a=g+c.sqrt(h)*5}if(a<0){var g=i*(r-u-s),h=-a-g;if(h>0)a=-g-c.sqrt(h)*5}}if(H-hb<-2)jb=0;else if(H-hb>2)jb=-1;hb=H;H=a;sb=G-H/i/(Y||1);if(H&&x&&!yb){b.yb(e);if(!M)z.ee(sb);else z.de(sb)}}}}}function bb(){qc();if(B){B=l;b.H();b.A(f,"mousemove",Bb);b.A(f,"touchmove",Bb);P=H;z.R();var a=w.G();g.f(i.Md,t(a),a,t(G),G);E&12&&Pb();ec(d)}}function jc(c){if(P){b.Ae(c);var a=b.Gb(c);while(a&&v!==a){a.tagName=="A"&&b.yb(c);try{a=a.parentNode}catch(d){break}}}}function Jb(a){C[s];s=t(a);tb=C[s];Tb(a);return s}function Dc(a,b){x=0;Jb(a);g.f(i.rd,t(a),b)}function Tb(a,c){wb=a;b.e(S,function(b){b.Lb(t(a),a,c)})}function sc(){var b=i.cd||0,a=X;if(ob)a&1&&(a&=1);i.cd|=a;return O=a&~b}function qc(){if(O){i.cd&=~X;O=0}}function Xb(){var a=b.nb();b.O(a,V);b.z(a,"absolute");return a}function t(a){return(a%r+r)%r}function kc(b,d){if(d)if(!D){b=c.min(c.max(b+wb,0),r-u);d=l}else if(D&2){b=t(b+wb);d=l}cb(b,a.Eb,d)}function xb(){b.e(S,function(a){a.Wb(a.Cb.Ke<=F)})}function hc(){if(!F){F=1;xb();if(!B){E&12&&ec();E&3&&C[s].ac()}}}function Ec(){if(F){F=0;xb();B||!(E&12)||gc()}}function ic(){V={Fb:K,zb:J,i:0,j:0};b.e(T,function(a){b.O(a,V);b.z(a,"absolute");b.qb(a,"hidden");b.B(a)});b.O(gb,V)}function ab(b,a){cb(b,a,d)}function cb(g,f,j){if(Rb&&(!B&&(F||!(E&12))||a.Wc)){M=d;B=l;z.R();if(f==k)f=Vb;var e=Cb.fb(),b=g;if(j){b=e+g;if(g>0)b=c.ceil(b);else b=c.floor(b)}if(D&2)b=t(b);if(!(D&1))b=c.max(0,c.min(b,r-u));var i=(b-e)%r;b=e+i;var h=e==b?0:f*c.abs(i);h=c.min(h,f*u*1.5);z.ub(e,b,h||1)}}g.Xc=function(){if(!N){N=d;C[s]&&C[s].ac()}};function W(){return b.m(y||p)}function nb(){return b.n(y||p)}g.U=W;g.Z=nb;function Eb(c,d){if(c==k)return b.m(p);if(!y){var a=b.nb(f);b.sc(a,b.sc(p));b.Db(a,b.Db(p));b.C(a,"block");b.z(a,"relative");b.K(a,0);b.J(a,0);b.qb(a,"visible");y=b.nb(f);b.z(y,"absolute");b.K(y,0);b.J(y,0);b.m(y,b.m(p));b.n(y,b.n(p));b.Fc(y,"0 0");b.I(y,a);var h=b.pb(p);b.I(p,y);b.L(p,"backgroundImage","");b.e(h,function(c){b.I(b.g(c,"noscale")?p:a,c);b.g(c,"autocenter")&&Lb.push(c)})}Y=c/(d?b.n:b.m)(y);b.we(y,Y);var g=d?Y*W():c,e=d?c:Y*nb();b.m(p,g);b.n(p,e);b.e(Lb,function(a){var c=b.wd(b.g(a,"autocenter"));b.Ad(a,c)})}g.re=Eb;n.call(g);g.M=p=b.vb(p);var a=b.kb({cb:0,ne:1,Tb:1,Rb:0,Gc:l,rb:1,ob:d,Wc:d,Ub:1,rc:3e3,qc:1,Eb:500,ge:e.zd,Oc:20,Ib:0,Y:1,Cc:0,ye:1,Vb:1,tc:1},fc);a.ob=a.ob&&b.Sd();if(a.od!=k)a.rc=a.od;if(a.pd!=k)a.Cc=a.pd;var fb=a.Vb&3,tc=(a.Vb&4)/-4||1,mb=a.Le,I=b.kb({ab:q,ob:a.ob},a.Qe);I.Yb=I.Yb||I.Pe;var Fb=a.Oe,Z=a.qd,eb=a.Ne,Q=!a.ye,y,v=b.u(p,"slides",Q),gb=b.u(p,"loading",Q)||b.nb(f),Nb=b.u(p,"navigator",Q),dc=b.u(p,"arrowleft",Q),ac=b.u(p,"arrowright",Q),Mb=b.u(p,"thumbnavigator",Q),pc=b.m(v),nc=b.n(v),V,T=[],uc=b.pb(v);b.e(uc,function(a){if(a.tagName=="DIV"&&!b.g(a,"u"))T.push(a);else b.Hc()&&b.s(a,(b.s(a)||0)+1)});var s=-1,wb,tb,r=T.length,K=a.Bc||pc,J=a.Fd||nc,Wb=a.Ib,zb=K+Wb,Ab=J+Wb,bc=fb&1?zb:Ab,u=c.min(a.Y,r),lb,x,O,yb,S=[],Qb,Sb,Ob,cc,Cc,N,E=a.qc,lc=a.rc,Vb=a.Eb,rb,ib,kb,Rb=u<r,D=Rb?a.rb:0,X,P,F=1,M,B,R,ub=0,vb=0,H,hb,jb,Cb,w,U,z,Ub=new oc,Y,Lb=[];if(r){if(a.ob)Kb=function(a,c,d){b.Ab(a,{V:c,bb:d})};N=a.Gc;g.Cb=fc;ic();b.v(p,"jssor-slider",d);b.s(v,b.s(v)||0);b.z(v,"absolute");lb=b.hb(v,d);b.Ob(lb,v);if(mb){cc=mb.Me;rb=mb.ab;ib=u==1&&r>1&&rb&&(!b.ad()||b.mc()>=8)}kb=ib||u>=r||!(D&1)?0:a.Cc;X=(u>1||kb?fb:-1)&a.tc;var Gb=v,C=[],A,L,Db=b.Td(),ob=Db.Wd,G,qb,Ib,sb;Db.Yc&&b.L(Gb,Db.Yc,([j,"pan-y","pan-x","none"])[X]||"");U=new zc;if(ib)A=new rb(Ub,K,J,mb,ob);b.I(lb,U.Jb);b.qb(v,"hidden");L=Xb();b.L(L,"backgroundColor","#000");b.Zb(L,0);b.Ob(L,Gb.firstChild,Gb);for(var db=0;db<T.length;db++){var wc=T[db],yc=new xc(wc,db);C.push(yc)}b.B(gb);Cb=new Ac;z=new mc(Cb,U);if(X){b.a(v,"mousedown",Yb);b.a(v,"touchstart",rc);b.a(v,"dragstart",Hb);b.a(v,"selectstart",Hb);b.a(f,"mouseup",bb);b.a(f,"touchend",bb);b.a(f,"touchcancel",bb);b.a(h,"blur",bb)}E&=ob?10:5;if(Nb&&Fb){Qb=new Fb.ab(Nb,Fb,W(),nb());S.push(Qb)}if(Z&&dc&&ac){Z.rb=D;Z.Y=u;Sb=new Z.ab(dc,ac,Z,W(),nb());S.push(Sb)}if(Mb&&eb){eb.Rb=a.Rb;Ob=new eb.ab(Mb,eb);S.push(Ob)}b.e(S,function(a){a.Qb(r,C,gb);a.lb(o.lc,kc)});b.L(p,"visibility","visible");Eb(W());b.a(v,"click",jc,d);b.a(p,"mouseout",b.Dc(hc,p));b.a(p,"mouseover",b.Dc(Ec,p));xb();a.Tb&&b.a(f,"keydown",function(b){if(b.keyCode==37)ab(-a.Tb);else b.keyCode==39&&ab(a.Tb)});var pb=a.Rb;if(!(D&1))pb=c.max(0,c.min(pb,r-u));z.ub(pb,pb,0)}};i.Ce=21;i.jd=22;i.Md=23;i.ie=24;i.he=25;i.Be=26;i.ae=27;i.id=28;i.le=202;i.rd=203;i.qe=206;i.Id=207;i.ld=208;i.bd=209;var o={lc:1};var r=function(a,g,h){var c=this;n.call(c);var r,q,e,f,i;b.m(a);b.n(a);function k(a){c.f(o.lc,a,d)}function p(c){b.P(a,c||!h.rb&&e==0);b.P(g,c||!h.rb&&e>=q-h.Y);r=c}c.Lb=function(b,a,c){if(c)e=a;else{e=b;p(r)}};c.Wb=p;var m;c.Qb=function(c){q=c;e=0;if(!m){b.a(a,"click",b.X(j,k,-i));b.a(g,"click",b.X(j,k,i));b.Ic(a);b.Ic(g);m=d}};c.Cb=f=b.kb({Ac:1},h);i=f.Ac;if(f.vc==l){b.v(a,"noscale",d);b.v(g,"noscale",d)}if(f.bc){b.v(a,"autocenter",f.bc);b.v(g,"autocenter",f.bc)}};function q(e,d,c){var a=this;m.call(a,0,c);a.Lc=b.uc;a.Sc=0;a.Qc=c}jssor_1_slider_init=function(){var e={Ub:4,Eb:160,Bc:500,Ib:3,Y:4,qd:{ab:r,Ac:4}},d=new i("jssor_1",e);function f(){var e=b.pe(d.M,"slides");if(e){var c=e[1];if(c){var a=b.u(c,"ad");if(!a){a=b.nb();b.Db(a,"position:absolute;top:0px;right:0px;width:80px;height:20px;background-color:rgba(255,255,140,0.5);font-size: 12px;line-height: 20px;text-align:center;");b.He(a,"Leonard Scarf");b.I(c,a)}}}}f();function a(){var b=d.M.parentNode.clientWidth;if(b){b=c.min(b,809);d.re(b)}else h.setTimeout(a,30)}a();b.a(h,"load",a);b.a(h,"resize",a);b.a(h,"orientationchange",a)}})(window,document,Math,null,true,false)</script>
<style>
* {padding: 0;margin: 0; -webkit-box-sizing: border-box; -moz-box-sizing: border-box;box-sizing: border-box;}
nav {width: 90%;height:auto;margin: 0px auto;}
nav ul {list-style: none;overflow: hidden;}
nav small {color: #aaa; font: 12px Tahoma, sans-serif;text-transform: none;}
nav li a {background: #000;border: 1px solid #fff;border-top:none;border-bottom:none;color: #ffffcc;display: block;float: right;font: 15px 'Tahoma', sans-serif;padding: 10px;text-align: center;text-decoration: none;width: 12.5%;-webkit-transition: background 0.5s ease;-moz-transition: background 0.5s ease;-o-transition: background 0.5s ease;-ms-transition: background 0.5s ease;transition: background 0.5s ease;}
nav li a:hover {background: #555;}
nav li:first-child a {border-right:none;}
nav li:last-child a {border-left:none;}
@media only screen and (max-width : 1220px),only screen and (max-device-width : 1220px){
nav li a {font-size: 13px;}
nav small {font-size: 11px;}}
@media only screen and (max-width : 930px),only screen and (max-device-width : 930px){
nav li a {width: 25%;border-bottom: 1px solid #fff;font-size: 14px;}
nav li:last-child a, nav li:nth-child(4) a {border-left:none;}
nav li:last-child a, nav li:nth-child(5) a {border-right:none;}
nav li:nth-child(5) a, nav li:nth-child(6) a, nav li:nth-child(7) a, nav li:nth-child(8) a {border-bottom:none;}}
@media only screen and (max-width : 580px),only screen and (max-device-width : 580px){
nav li a {width: 50%;font-size: 14px;padding-top: 12px;padding-bottom: 12px;}
nav li:nth-child(even) a {border-left: none;}
nav li:nth-child(odd) a {border-right: none;}
nav li:nth-child(5) a, nav li:nth-child(6) a {border-bottom: 1px solid #fff;}}
.header-distributed{background-color: #000000;box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.12);box-sizing: border-box;width: 100%;text-align: left;font: bold 16px sans-serif;height: 120px;padding: 30px 25px;margin-top: 5px;}
.header-distributed .header-left,.header-distributed .header-center,.header-distributed .header-right{display: inline-block;vertical-align: top;}
.header-distributed .header-left{width: 40%;}
.header-distributed h3{color:  #ffffff;font: normal 40px 'Cookie', cursive;margin: 0;}
.header-distributed h3 span{color:  #5383d3;}
.header-distributed h1{color: #ffffcc;font-size: 24px ;padding: 5px 5px;margin: 0;}
.header-distributed h1 strong{font-weight: 15px;}
.header-distributed .header-right{width: 50%;text-align: right;margin-top: 30px;}
@media (max-width: 880px) {
.header-distributed{font: bold 14px sans-serif;height: 150px;}
.header-distributed h1{font-size: 18px;}
.header-distributed .header-left,.header-distributed .header-center,.header-distributed .header-right{display: block;width: 100%;margin-top: 10px;text-align: center;}
.header-distributed .header-center i{margin-left: 0;}}
@font-face {font-family: 'FontAwesome';src: url('../../../fonts/fontawesome-webfont.eot?v=4.6.3');src: url('../../../fonts/fontawesome-webfont.eot?#iefix&v=4.6.3') format('embedded-opentype'), url('../../../fonts/fontawesome-webfont.woff2?v=4.6.3') format('woff2'), url('../../../fonts/fontawesome-webfont.woff?v=4.6.3') format('woff'), url('../../../fonts/fontawesome-webfont.ttf?v=4.6.3') format('truetype'), url('../../../fonts/fontawesome-webfont.svg?v=4.6.3#fontawesomeregular') format('svg');font-weight: normal;font-style: normal;}
.fa {display: inline-block;font: normal normal normal 14px/1 FontAwesome;font-size: inherit;text-rendering: auto; -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;}
.fa-flip-vertical { -ms-filter: "progid:DXImageTransform.Microsoft.BasicImage(rotation=2, mirror=1)";-webkit-transform: scale(1, -1); -ms-transform: scale(1, -1);transform: scale(1, -1);}
.fa-envelope:before {content: "\f0e0";}
.fa-phone:before {content: "\f095";}
.fa-map-marker:before {content: "\f041";}
.fa-facebook:before {content: "\f09a";}
.fa-paper-plane-o:before {content: "\f1d8";}
.fa-paper-plane:before {content: "\f1d9";}
.fa-instagram:before {content: "\f16d";}
.fa-google:before {content: "\f1a0";}
.fa-cogs:before {content: "\f085";}
hr.style-two {border: 0;height: 2px;background-image: linear-gradient(to right, rgba(255, 255, 255, 200), rgba(1, 1, 1, 0), rgba(100, 100, 1, 100));}
hr.style-one {border: 0;height: 1px;background-image: linear-gradient(to left, rgba(255, 255, 255, 200), rgba(1, 1, 1, 0.5), rgba(100, 100, 1, 100));}
.footer-up{background-color: #000000;width: 100%;text-align: center;font-family:'Tahoma', Geneva, sans-serif;font-size:16px;padding: 0px 50px;}
.footer-up .footer-center{display: inline-block;vertical-align: top;width: 100%;}
.footer-up .footer-links{color:  #ffffcc;margin: 20px 0 12px;padding: 0;}
.footer-up .footer-links a{display:inline-block;line-height: 2.8;text-decoration: none;color:  inherit;}
.footer-up .footer-links a:hover { color: #767676;}
.footer-distributed{background-color: #000000;box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.12);box-sizing: border-box;width: 100%;text-align: right;font: bold 16px sans-serif;padding: 0px 50px;margin-top: 100px;}
.footer-distributed .footer-left,
.footer-distributed .footer-center,
.footer-distributed .footer-right{display: inline-block;vertical-align: top;}
.footer-distributed .footer-left{width: 40%;}
.footer-distributed h3{color:  #ffffff;font: normal 36px 'Cookie', cursive;margin: 0;}
.footer-distributed h3 span{color:  #5383d3;}
.footer-distributed .footer-links{color:  #ffffff;margin: 20px 0 12px;padding: 0;}
.footer-distributed .footer-links a{display:inline-block;line-height: 1.8;text-decoration: none;color:  inherit;}
.footer-distributed .footer-links a:hover { color: #767676;}
.footer-distributed .footer-company-name{color:  #8f9296;font-size: 14px;font-weight: normal;margin: 0;}
.footer-distributed .footer-center{width: 35%;}
.footer-distributed .footer-center i{background-color:  #33383b;color: #ffffff;font-size: 25px;width: 38px;height: 38px;border-radius: 50%;text-align: center;line-height: 42px;margin: 10px 15px;vertical-align: middle;}
.footer-distributed .footer-center i.fa-envelope{font-size: 17px;line-height: 38px;}
.footer-distributed .footer-center p{display: inline-block;color: #ffffff;vertical-align: middle;margin:0;text-align: right;}
.footer-distributed .footer-center p span{display:block;font-weight: normal;font-size:14px;line-height:2;}
.footer-distributed .footer-center p a{color:  #5383d3;text-decoration: none;;}
.footer-distributed .footer-right{width: 20%;text-align: right;}
.footer-distributed .footer-company-about{line-height: 20px;color:  #92999f;font-size: 13px;font-weight: normal;margin: 0;}
.footer-distributed .footer-company-about span {display: block;color:  #ffffff;font-size: 14px;font-weight: bold;margin-bottom: 20px;}
.footer-distributed .footer-company-about  a{color:  #ffffff;}
.footer-distributed .footer-company-about span :hover{color: #767676;}
.footer-distributed .footer-icons{margin-top: 25px;}
.footer-distributed .footer-icons a{display: inline-block;width: 35px;height: 35px;cursor: pointer;background-color:  #33383b;border-radius: 2px;font-size: 20px;color: #ffffff;text-align: center;line-height: 35px;margin-right: 3px;margin-bottom: 5px;}
.footer-distributed .footer-icons a:hover{background-color: #767676; -ms-filter: "progid:DXImageTransform.Microsoft.BasicImage(rotation=0, mirror=1)"; -webkit-transform: scale(-1, 1); -ms-transform: scale(-1, 1);transform: scale(-1, 1);}
@media (max-width: 880px) {
.footer-distributed{font: bold 14px sans-serif;}
.footer-distributed .footer-left,.footer-distributed .footer-center,.footer-distributed .footer-right{display: block;width: 100%;margin-bottom: 40px;text-align: center;}
.footer-distributed .footer-center p{text-align: center;}
.footer-distributed .footer-center i{margin-right: 0;}}
p {margin: 0 0 20px; line-height: 1.5;}
.myslide {position: relative; top: 50px;}
.maintab { width: calc(100% - 550px); height: auto; position: relative;  }
@media screen and (max-width: 900px) { .maintab {width: 100%; height: auto; position: relative; margin-right: 5px; } }
.content {background: #ffffcc; color: #373737; line-height:30px; }
.content > div {display: none; padding: 20px 25px 5px; }
input {display: none; }
label {display: inline-block; padding: 15px 25px; font-weight: 600; text-align: center; }
label:hover {color: #fff; cursor: pointer;}
input:checked + label {background: #ffffcc; color: #111;}
#tab1:checked ~ .content #content1,#tab2:checked ~ .content #content2,#tab3:checked ~ .content #content3,#tab4:checked ~ .content #content4 {display: block;}
@media screen and (max-width: 400px) { label {padding: 15px 10px;}}
h3.one {position: relative;margin-top: 80px;margin-bottom: 80px;text-align:center;}
h3.one:before {content: "";display: block;border-top: solid 3px white;width: 100%;height: 1px;position: absolute;top: 50%;z-index: 1;}
h3.one span {font-family: 'Raleway', Arial, sans-serif;font-weight: 200;font-size: 12px;font-size: 3.0vw;background: #000000;padding: 0 20px;position: relative;z-index: 5;}
.head{margin:0 auto;width: 100%;position: relative;margin-top:20px;}
.head1{text-align:right;margin-right:30px;}
.head2{text-align:left;margin-left:30px;}
.head1 a, .head2 a{   color: #b48608;text-decoration:none;}
.button {background-color: #4CAF50; /* Green */border: none;color: white;padding: 12px 20px;text-align: center;text-decoration: none;display: inline-block;font-size: 16px;margin: 4px 2px;cursor: pointer;border-radius: 12px;}
input[type=number] {padding: 12px 20px;box-sizing: border-box;display: inline-block;border: 1px solid #555;outline: none;border-radius: 12px;}
input[type=number]:focus {background-color: lightblue;}
.right{float:right}.left{float:left;}.center{text-align:center}
.add_to_cart{ float:left; padding-left:10px;margin-right:10px;}
.clearfix{clear:both;}
.product_name{ direction:rtl; margin-top:40px;margin-left:10px; padding:20px 20px; font-size: 12px; color:#b48608;}
.was_price{text-decoration:line-through;color:#9da6ae;font-style:italic;text-shadow:none;font-weight:normal}
.kharid{text-align:left;width:30%;height:auto;margin:20px 20px;marign-right:10px;}
.zoom-desc h3{font-family:Tahoma, Geneva, sans-serif;font-size:14px;text-align:right;color:#b48608;letter-spacing:1px;margin-top:10px;margin-bottom:10px;}
.thumbzoom{display:block;position:relative;float:right;margin-bottom:20px;}
.zoom-section{display:block;width:500px;position:relative;float:right;margin-top:20px;margin-right:30px;margin-left:20px;}
.zoom-desc{display:block;position:relative;float:right;}
.zoom-small-image{margin-bottom:20px;}
.zoom-tiny-image{margin:0px;}
.zoom-tiny-image:hover{border:1px solid #C00;}
@media screen and (max-width: 900px) {.zoom-section{width:100%;}.zoom-small-image{margin-right:30%;margin-left:30%;vertical-align: middle;width: 500px; height: auto;}.kharid{width:100%;}}
@media screen and (max-width: 650px) {.zoom-small-image{margin-right:10%;margin-left:10%;vertical-align: middle;width: 500px; height: auto;}
.zoom-small-image img {height: auto;width: 500px;vertical-align: middle;margin-right:1%;margin-left:1%;}}
@media screen and (max-width: 480px){.zoom-small-image{height: auto;width:100%;}
.zoom-small-image img {height: auto;width:100%;}}
body{ background: #000000; color: #ffffcc; overflow: scroll; overflow-x:hidden; overflow-y:auto;}
</style>
<style>.jssora03l,.jssora03r{display:block;position:absolute;width:55px;height:55px;cursor:pointer;background:url('../../../images/a03.png') no-repeat;overflow:hidden}.jssora03l{background-position:-3px -33px}.jssora03r{background-position:-63px -33px}.jssora03l:hover{background-position:-123px -33px}.jssora03r:hover{background-position:-183px -33px}.jssora03l.jssora03ldn{background-position:-243px -33px}.jssora03r.jssora03rdn{background-position:-303px -33px}</style>
</head>
<body  oncontextmenu="return false" >
<header class="header-distributed">
<div class="header-left">
<h3>Leonard<span>Scarf</span></h3>
</div>
<div class="header-right">
<h1><strong>شال و روسری</strong> لئونارد </h1>
</div>
<hr class="style-two">
</header>
<nav>
<ul>
<li><a href="https://www.leonardscarf.com">صفحه اصلی<br /> <small>شال و روسری</small></a></li>
<li><a href="https://www.leonardscarf.com/search/">جستجو<br /> <small>تمام ارشیو</small></a></li>
<li><a href="https://www.leonardscarf.com/scarf/">روسری<br /> <small>جستجو روسری</small></a></li>
<li><a href="https://www.leonardscarf.com/shawl/">شال<br /> <small>جستجو شال</small></a></li>
<?php if (!isset($_SESSION['usernamelogin'])) { ?>
<li><a href="https://www.leonardscarf.com/register/register">ثبت نام<br /> <small>عضویت</small></a></li>
<li><a href="https://www.leonardscarf.com/register/loginuser">ورود<br /> <small>کاربر</small></a></li>
<?php } else { 	?>
<li><a href="https://www.leonardscarf.com/register/logout"><?php echo $_SESSION['usernamelogin']; ?><br /> <small>خروج</small></a></li>
<li><a href="https://www.leonardscarf.com/pricelist">لیست قیمت<br /> <small>شال و روسری</small></a></li>
<?php } ?>
<li><a href="https://www.leonardscarf.com/contactus">تماس با لئونارد<br /> <small>تماس بگیرید</small></a></li>
<li><a href="https://www.leonardscarf.com/about">درباره لئونارد<br /> <small>توضیحات</small></a></li>
</ul>
</nav>
<div class="head">
<div class="head1" >&laquo;&nbsp;
<a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-14" title="شال نخی عریض کار شده">قبلی</a>&nbsp; |
<a href="https://www.leonardscarf.com/view/shawl/cotton/shawl-16" title="شال حریر مجلسی">بعدی </a>&nbsp;&raquo;
</div>
<div class="head2" >
<a href="https://www.leonardscarf.com/search/" title="جستجو شال و روسری" >&lt; جستجو | تمام شال و روسری ها</a>
</div>
</div>
<div class="zoom-section">
<div class="zoom-small-image">
<a href='https://www.leonardscarf.com/images/shawl/cotton/shawl-cotton-15-1050.jpg' class = 'cloud-zoom' id="zoom1" rel="position:'inside',showTitle:false,adjustX:-4,adjustY:-4"><img src="https://www.leonardscarf.com/images/shawl/cotton/shawl-cotton-15-500.jpg" alt='شال نخی گیپوردار لئونارد' title="شال نخی گیپوردار لئونارد" /></a>
</div>
</div>
<div class="product_name">
<h1>شال نخی گیپوردار لئونارد</h1>
</div>
<p>
<span class="sold_out"></span>
<span style="font-size:1.6rem; padding-left:10px;">قیمت :0 تومان</span>
<span class="was_price">0 تومان</span>
</p>
<form class="kharid"  method="post" id="product-form-1">
<input type="number" min="1" size="1"  name="quantity" id="quantity" value="1" max="1" />
<label for="quantity" style="text-align:right; padding-left:10px;padding-top:15px; padding-right:10px; font-size: 1.0rem;">تعداد</label>
<div class="add_to_cart">
<button class="button" type="submit" name="add"  disabled>خرید</button>
</div>
</form><hr />
<div class="maintab" dir="rtl">
<input id="tab1" type="radio" name="tabs"  checked>
<label for="tab1">توضیحات</label>
<input id="tab2" type="radio" name="tabs">
<label for="tab2">جزئیات</label>
<input id="tab3" type="radio" name="tabs">
<label for="tab3">مرجوعی</label>
<input id="tab4" type="radio" name="tabs">
<label for="tab4">نحوه ارسال</label>
<div class="content">
<div id="content1">
<p style="line-height:40px;">
انعطاف زیادی که در بین بافت های شال نخی لئونارد وجود دارد باعث نرمی دوخت پارچه و خوش حالت بودن آن می شود. شرکت لئونارد باتوجه به تغییر فصل و رسید به فصل سرما وبارندگی ضمن تهیه پارچه ای مناسب فصل سرما به لطافت و نرمی پارچه نیز اهمیت ویژه ای اختصاص داده و شال و روسری گرم و لیطف و با کیفیتی در اختیار شما هموطنان ارجمند قرار میدهد.
</p><br><br><br><br><br><br></div>
<div id="content2">
<ul>
<li><span style="line-height: 1.5;">مدل : شال</span></li>
<li><span style="line-height: 1.5;">نوع جنس : نخی</span></li>
<li><span style="line-height: 1.5;">سایز : بلند</span></li>
<li><span style="line-height: 1.5;">تعداد رنگ : 6 رنگ</span></li>
<li><span style="line-height: 1.0;">شستشو : با آب ولرم و آب سرد</span></li>
<li><span style="line-height: 1.0;">مواد سفید کننده استفاده نشود...</span></li>
<li><span style="line-height: 1.0;"> قابلیت اتو دارد</span></li>
<li><strong><span style="line-height: 1.5;">تحت لیسانس ایتالیا</span><br><br><br><br></strong></li>
</ul>
</div>
<div id="content3">
<h2 style="margin: 0px 0px 0.75em; padding: 0px; border: 0px; font-family: Asap; font-size: 26px; font-weight: normal; font-stretch: inherit; line-height: 23.7999992370605px; color: #737373; text-rendering: optimizeLegibility;"><span style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: 14px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: 1.2;">
این کالا قابل برگشت نمی باشد</span></h2><br><br><br><br><br><br><br><br><br><br>
</div>
<div id="content4">
<p style="margin: 0px 0px 1em; line-height: 1.4; font-family: &#039;Helvetica Neue&#039;, Helvetica, Arial, sans-serif; font-size: 15px; text-align: center;"><span style="color: #e06666;">
<strong>تمام سفارشات از تهران ارسال خواهد شد</strong></span>&nbsp;<strong><span style="color: #ff0000;">&nbsp;</span></strong>&nbsp;</p><p style="margin: 0px 0px 1em; line-height: 1.4; font-family: &#039;Helvetica Neue&#039;, Helvetica, Arial, sans-serif; font-size: 15px; text-align: center;">
<strong>مراحل ارسال  دو روز کاری بلافاصله پس از ثبت سفارش توسط شما به طول می انجامد</strong></p><p style="margin: 0px 0px 1em; line-height: 1.4; font-family: &#039;Helvetica Neue&#039;, Helvetica, Arial, sans-serif; font-size: 15px; text-align: center;">
تمامی سفارشات دارای کد رهگیری می باشد.</p><h3 style="margin: 0px 0px 1em; line-height: 1.4; font-family: &#039;Helvetica Neue&#039;, Helvetica, Arial, sans-serif;">
ایران</h3><p style="margin: 0px 0px 1em; line-height: 1.4; font-family: &#039;Helvetica Neue&#039;, Helvetica, Arial, sans-serif; font-size: 15px;"><em style="line-height: 1.2;">
<strong>هزینه ارسال با پست 8000 تومان.
و با پیک  فقط داخل شهر تهران 15000 تومان می باشد.</strong></em></p>
<p><span><em>لطفا توجه داشته باشید , شرکت لئونارد تمامی تلاش خود را میکند تا کالای سفارشی شما در زمان مقرر به دست شما برسد, با تشکر از حسن انتخاب شما </em></span><br><br><br><br><br><br><br></p></div></div>
</div>
<br><br><br><br>
<? include 'cotton-slide.php'; ?>
<footer class="footer-distributed" dir="rtl">
<hr class="style-one">
<div class="footer-left">
<h3>Leonard<span>Scarf</span></h3>
<p class="footer-links">
<a href="https://www.leonardscarf.com/index">صفحه اصلی</a>&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/register/register">ثبت نام</a>&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/register/loginuser">ورود به سایت</a>&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/contactus">تماس با ما</a>&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/about">درباره ما</a>&nbsp;&nbsp;
</p>
<p class="footer-company-name">»Leonard Scarf &copy; 2015</p>
</div>
<div class="footer-center">
<div>
<i class="fa fa-map-marker"></i>
<p>ایران , تهران<span>15 خرداد بین الحرمین روبری مسجد بین الحرمین کوچه تکیه پلاک 3 (جنب سرای عزیزیان)</span></p>
</div>
<div>
<i class="fa fa-phone"></i>
<p dir="ltr">+982155555555</p>
</div>
<div>
<i class="fa fa-envelope"></i>
<p><a href="mailto:admin@leonardscarf.com.com">admin@leonardscarf.com</a></p>
</div>
</div>
<div class="footer-right">
<p class="footer-company-about">
<span><a href="https://www.leonardscarf.com/about">درباره شرکت لئونارد</a></span>
لئونارد ارائه کننده برترین مدلهای شال و روسری
</p>
<div class="footer-icons">
<a href="https://www.facebook.com/leonardazin"><i class="fa fa-facebook"></i></a>
<a href="https://telegram.me/joinchat/CEmNSjvmKui9SUKYbzrrqw"><i class="fa fa-paper-plane"></i></a>
<a href="https://www.instagram.com/leonardscarf/?ref=badge"><i class="fa fa-instagram"></i></a>
<a href="https://plus.google.com/118304422008766935997"><i class="fa fa-google"></i></a>
</div>
</div>
</footer>
<div class="footer-up">
<hr class="style-two">
<div class="footer-center" dir="rtl">
<p class="footer-links">
<a href="https://www.leonardscarf.com/honours">افتخارات</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/rules">قوانین و مقررات</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/complaints">شکایات</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="https://www.leonardscarf.com/sitemap.php">نقشه سایت</a>&nbsp;&nbsp;&nbsp;&nbsp;
</p>
</div>
</div>
</body>
</html>